"""A module to store initial values for various database models in the app"""
#IMPORTS
from datetime import datetime,date,timedelta

###
facility = {
  "facility_id":f"dental-futuresmile",          #
  "name":"future smile specialized dental clinic",
  "postcode":67102,
  "category":"dental",
  "level":"clinic",
  "certifications":["NTA 4:Basic Technician Certificate","NTA 5:Technician Certificate","NTA 6:Ordinary Diploma","NTA 7:Higher Diploma","NTA 8:Bachelor's Degree","NTA 9:Master's Degree","NTA 10:Doctorate Degree"],
  "designations":["MDent","DDS","ADO","DT","Pharm Tech","Pharmacist","Medical Doctor","Receptionist","Radiographer","Radiologist","Registered Nurse","Enrolled Nurse","Medical Attendant","Laboratory Technician"],
  "primary_roles":["Doctor","Nurse","Receptionist","Radiographer","Office Cleaner"],
  "secondary_roles":[None,"Director"],
  "services":["Consultation","Imaging","Procedure","Surgery"],
  "medicine_types":["Antibiotic","Analgesic","Antiseptic","Antifungal","Accessory"],
  "vendors":[],
  "mos":[2,4],
  "occupations":["Business","Child","Student","Housewife","Farmer","Transportation","Restaurant","Reception","Cashier","Doctor","Nurse","Pharmacist","Laboratory Technician","Dentist","Physiotherap","Banker","Manager","Director","Accountant","Teacher","Lecturer","Headmaster","Headmistress","Police","Human Resource Officer","Software Developer","IT Officer"],
  "years_of_existence":[datetime.now().year],
}

default_subscription = {
  "facility_id":"dental-futuresmile",
  "receipt":"trial001",
  "tier":"standard",
  "cost":0,"paid_amount":0,"pending_amount":0,"end_time":datetime.now() + timedelta(days=30)
}

services = [
  {
    "service_id":"consult-dds",
    "name":"dentist consultation",
    "alternative_name":None,
    "type":"consultation",
    "schemes":[
      {
        "service_id":"consult-dds",
        "scheme_id":"cash-consult-dds",
        "scheme_name":"cash",
        "scheme_item_code":"consult-dds",
        "restricted":False,
        "prices":[
          {
            "scheme_id":"cash-consult-dds",
            "scheme_name":"cash",
            "standard":5000
          }
        ]
      },
      {
        "service_id":"consult-dds",
        "scheme_id":"nhif-consult-dds",
        "scheme_name":"nhif",
        "scheme_item_code":"10002",
        "restricted":False,
        "prices":[
          {
            "scheme_id":"nhif-consult-dds",
            "scheme_name":"nhif",
            "standard":7000
          }
        ]
      }
    ]
  },
  {
    "service_id":"extraction-permanent",
    "name":"permanent tooth extration",
    "alternative_name":None,
    "type":"procedure",
    "schemes":[
      {
        "service_id":"extraction-permanent",
        "scheme_id":"cash-extraction-permanent",
        "scheme_name":"cash",
        "scheme_item_code":"extraction-permanent",
        "restricted":False,
        "prices":[
          {
            "scheme_id":"cash-extraction-permanent",
            "scheme_name":"cash",
            "standard":15000
          }
        ]
      },
      {
        "service_id":"extraction-permanent",
        "scheme_id":"cash-extraction-permanent",
        "scheme_name":"nhif",
        "scheme_item_code":"6108",
        "restricted":False,
        "prices":[
          {
            "scheme_id":"cash-extraction-permanent",
            "scheme_name":"nhif",
            "standard":6500
          }
        ]
      }
    ]
  },
  {
    "service_id":"extraction-decidous",
    "name":"deciduous tooth extraction",
    "alternative_name":None,
    "type":"procedure",
    "schemes":[
      {
        "service_id":"extraction-decidous",
        "scheme_id":"cash-extraction-decidous",
        "scheme_name":"cash",
        "scheme_item_code":"extraction-decidous",
        "restricted":False,
        "prices":[
          {
            "scheme_id":"cash-extraction-decidous",
            "scheme_name":"cash",
            "standard":10000
          }
        ]
      },
      {
        "service_id":"extraction-decidous",
        "scheme_id":"nhif-extraction-decidous",
        "scheme_name":"nhif",
        "scheme_item_code":"6108",
        "restricted":False,
        "prices":[
          {
            "scheme_id":"nhif-extraction-decidous",
            "scheme_name":"nhif",
            "standard":5174
          }
        ]
      }
    ]
  },
  {
    "service_id":"disimpaction",
    "name":"tooth disimpaction",
    "alternative_name":"extraction of complex tooth",
    "type":"procedure",
    "schemes":[
      {
        "service_id":"disimpaction",
        "scheme_id":"cash-disimpaction",
        "scheme_name":"cash",
        "scheme_item_code":"disimpaction",
        "restricted":False,
        "prices":[
          {
            "scheme_id":"cash-disimpaction",
            "scheme_name":"disimpaction",
            "standard":35000
          }
        ]
      },
      {
        "service_id":"disimpaction",
        "scheme_id":"nhif-disimpaction",
        "scheme_name":"nhif",
        "scheme_item_code":"41041",
        "restricted":False,
        "prices":[
          {
            "scheme_id":"nhif-disimpaction",
            "scheme_name":"nhif",
            "standard":29250
          }
        ]
      }
    ]
  },
  {
    "service_id":"filling-temporary",
    "name":"temporary tooth filling",
    "alternative_name":None,
    "type":"procedure",
    "schemes":[
      {
        "service_id":"filling-temporary",
        "scheme_id":"cash-filling-temporary",
        "scheme_name":"cash",
        "scheme_item_code":"filling-temporary",
        "restricted":False,
        "prices":[
          {
            "scheme_id":"cash-filling-temporary",
            "scheme_name":"cash",
            "standard":30000
          }
        ]
      },
      {
        "service_id":"filling-temporary",
        "scheme_id":"nhif-filling-temporary",
        "scheme_name":"nhif",
        "scheme_item_code":"6517",
        "restricted":False,
        "prices":[
          {
            "scheme_id":"nhif-filling-temporary",
            "scheme_name":"nhif",
            "standard":36000
          }
        ]
      }
    ]
  },
  {
    "service_id":"filling-permanent",
    "name":"permanent tooth filling",
    "alternative_name":None,
    "type":"procedure",
    "schemes":[
      {
        "service_id":"filling-permanent",
        "scheme_id":"cash-filling-permanent",
        "scheme_name":"cash",
        "scheme_item_code":"filling-permanent",
        "restricted":False,
        "prices":[
          {
            "scheme_id":"cash-filling-permanent",
            "scheme_name":"cash",
            "standard":40000
          }
        ]
      },
      {
        "service_id":"filling-permanent",
        "scheme_id":"nhif-filling-permanent",
        "scheme_name":"nhif",
        "scheme_item_code":"6515",
        "restricted":False,
        "prices":[
          {
            "scheme_id":"nhif-filling-permanent",
            "scheme_name":"nhif",
            "standard":42120
          }
        ]
      }
    ]
  },
  {
    "service_id":"dental-splinting",
    "name":"dental splinting",
    "alternative_name":"splinting of teeh per quadrant",
    "type":"procedure",
    "schemes":[
      {
        "service_id":"dental-splinting",
        "scheme_id":"cash-dental-splinting",
        "scheme_name":"cash",
        "scheme_item_code":"dental-splinting",
        "restricted":False,
        "prices":[
          {
            "scheme_id":"cash-dental-splinting",
            "scheme_name":"cash",
            "standard":50000
          }
        ]
      },
      {
        "service_id":"dental-splinting",
        "scheme_id":"nhif-dental-splinting",
        "scheme_name":"nhif",
        "scheme_item_code":"6267",
        "restricted":False,
        "prices":[
          {
            "scheme_id":"nhif-dental-splinting",
            "scheme_name":"nhif",
            "standard":10000
          }
        ]
      }
    ]
  },
  {
    "service_id":"imf",
    "name":"intermaxillary fixation",
    "alternative_name":"fixing broken jaw",
    "type":"surgery",
    "schemes":[
      {
        "service_id":"imf",
        "scheme_id":"cash-imf",
        "scheme_name":"cash",
        "scheme_item_code":"imf",
        "restricted":False,
        "prices":[
          {
            "scheme_id":"cash-imf",
            "scheme_name":"cash",
            "standard":350000
          }
        ]
      },
      {
        "service_id":"imf",
        "scheme_id":"nhif-imf",
        "scheme_name":"nhif",
        "scheme_item_code":"41055",
        "restricted":False,
        "prices":[
          {
            "scheme_id":"nhif-imf",
            "scheme_name":"nhif",
            "standard":100000
          }
        ]
      }
    ]
  },
  {
    "service_id":"gingivaectomy",
    "name":"gingivaectomy",
    "alternative_name":None,
    "type":"procedure",
    "schemes":[
      {
        "service_id":"gingivaectomy",
        "scheme_id":"cash-gingivaectomy",
        "scheme_name":"cash",
        "scheme_item_code":"gingivaectomy",
        "restricted":False,
        "prices":[
          {
            "scheme_id":"cash-gingivaectomy",
            "scheme_name":"cash",
            "standard":40000
          }
        ]
      },
      {
        "service_id":"gingivaectomy",
        "scheme_id":"nhif-gingivaectomy",
        "scheme_name":"nhif",
        "scheme_item_code":"41047",
        "restricted":False,
        "prices":[
          {
            "scheme_id":"nhif-gingivaectomy",
            "scheme_name":"nhif",
            "standard":35000
          }
        ]
      }
    ]
  },
  {
    "service_id":"frenotomy",
    "name":"Tongue tie release",
    "alternative_name":"frenotomy",
    "type":"procedure",
    "schemes":[
      {
        "service_id":"frenotomy",
        "scheme_id":"cash-frenotomy",
        "scheme_name":"cash",
        "scheme_item_code":"frenotomy",
        "restricted":False,
        "prices":[
          {
            "scheme_id":"cash-frenotomy",
            "scheme_name":"cash",
            "standard":25000
          }
        ]
      }
    ]
  },
  {
    "service_id":"whitening",
    "name":"teeth whitening",
    "alternative_name":"bleaching",
    "type":"procedure",
    "schemes":[
      {
        "service_id":"whitening",
        "scheme_id":"cash-whitening",
        "scheme_name":"cash",
        "scheme_item_code":"whitening",
        "restricted":False,
        "prices":[
          {
            "scheme_id":"cash-whitening",
            "scheme_name":"cash",
            "standard":120000
          }
        ]
      }
    ]
  },
  {
    "service_id":"anterior-dental-filling",
    "name":"pin addition dental filling (anterior)",
    "alternative_name":"anterior pin retained filling",
    "type":"procedure",
    "schemes":[
      {
        "service_id":"anterior-dental-filling",
        "scheme_id":"cash-anterior-dental-filling",
        "scheme_name":"cash",
        "scheme_item_code":"anterior-dental-filling",
        "restricted":False,
        "prices":[
          {
            "scheme_id":"cash-anterior-dental-filling",
            "scheme_name":"cash",
            "standard":50000
          }
        ]
      },
      {
        "service_id":"anterior-dental-filling",
        "scheme_id":"nhif-anterior-dental-filling",
        "scheme_name":"nhif",
        "scheme_item_code":"6518",
        "restricted":False,
        "prices":[
          {
            "scheme_id":"nhif-anterior-dental-filling",
            "scheme_name":"nhif",
            "standard":50000
          }
        ]
      }
    ]
  },
  {
    "service_id":"posterior-dental-filling",
    "name":"pin addition dental filling (posterior)",
    "alternative_name":"posterior pin retained filling",
    "type":"procedure",
    "schemes":[
      {
        "service_id":"posterior-dental-filling",
        "scheme_id":"cash-posterior-dental-filling",
        "scheme_name":"cash",
        "scheme_item_code":"posterior-dental-filling",
        "restricted":False,
        "prices":[
          {
            "scheme_id":"cash-posterior-dental-filling",
            "scheme_name":"cash",
            "standard":50000
          }
        ]
      },
      {
        "service_id":"posterior-dental-filling",
        "scheme_id":"nhif-posterior-dental-filling",
        "scheme_name":"nhif",
        "scheme_item_code":"6411",
        "restricted":False,
        "prices":[
          {
            "scheme_id":"nhif-posterior-dental-filling",
            "scheme_name":"nhif",
            "standard":60000
          }
        ]
      }
    ]
  },
  {
    "service_id":"braces",
    "name":"orthodontic braces",
    "alternative_name":"fixed orthodontic appliance fixing per jaw",
    "type":"procedure",
    "schemes":[
      {
        "service_id":"braces",
        "scheme_id":"cash-braces",
        "scheme_name":"cash",
        "scheme_item_code":"braces",
        "restricted":False,
        "prices":[
          {
            "scheme_id":"cash-braces",
            "scheme_name":"cash",
            "standard":600000
          }
        ]
      },
      {
        "service_id":"braces",
        "scheme_id":"nhif-braces",
        "scheme_name":"nhif",
        "scheme_item_code":"6522",
        "restricted":False,
        "prices":[
          {
            "scheme_id":"nhif-braces",
            "scheme_name":"nhif",
            "copayment":True,
            "standard":275000,
            "topup":325000
          }
        ]
      }
    ]
  },
  {
    "service_id":"dental-stones",
    "name":"dental stones/jewelry",
    "alternative_name":None,
    "type":"procedure",
    "schemes":[
      {
        "service_id":"dental-stones",
        "scheme_id":"cash-dental-stones",
        "scheme_name":"cash",
        "scheme_item_code":"dental-stones",
        "restricted":False,
        "prices":[
          {
            "scheme_id":"cash-dental-stones",
            "scheme_name":"cash",
            "standard":15000
          }
        ]
      }
    ]
  },
  {
    "service_id":"dental-flap",
    "name":"dental flap excision",
    "alternative_name":None,
    "type":"procedure",
    "schemes":[
      {
        "service_id":"dental-flap",
        "scheme_id":"cash-dental-flap",
        "scheme_name":"cash",
        "scheme_item_code":"dental-flap",
        "restricted":False,
        "prices":[
          {
            "scheme_id":"cash-dental-flap",
            "scheme_name":"cash",
            "standard":25000
          }
        ]
      },
      {
        "service_id":"dental-flap",
        "scheme_id":"nhif-dental-flap",
        "scheme_name":"nhif",
        "scheme_item_code":"41046",
        "restricted":False,
        "prices":[
          {
            "scheme_id":"nhif-dental-flap",
            "scheme_name":"nhif",
            "standard":35000
          }
        ]
      }
    ]
  },
  {
    "service_id":"veneer",
    "name":"dental veneer",
    "alternative_name":"tooth veneer",
    "type":"procedure",
    "schemes":[
      {
        "service_id":"veneer",
        "scheme_id":"cash-veneer",
        "scheme_name":"cash",
        "scheme_item_code":"veneer",
        "restricted":False,
        "prices":[
          {
            "scheme_id":"cash-veneer",
            "scheme_name":"cash",
            "standard":30000
          }
        ]
      }
    ]
  },
  {
    "service_id":"ceramic-crowning",
    "name":"ceramic dental crowning",
    "alternative_name":None,
    "type":"procedure",
    "schemes":[
      {
        "service_id":"ceramic-crowning",
        "scheme_id":"cash-ceramic-crowning",
        "scheme_name":"cash",
        "scheme_item_code":"ceramic-crowning",
        "restricted":False,
        "prices":[
          {
            "scheme_id":"cash-ceramic-crowning",
            "scheme_name":"cash",
            "standard":250000
          }
        ]
      }
    ]
  },
  {
    "service_id":"acrylic-crowning",
    "name":"acrylic dental crowning",
    "alternative_name":None,
    "type":"procedure",
    "schemes":[
      {
        "service_id":"acrylic-crowning",
        "scheme_id":"cash-acrylic-crowning",
        "scheme_name":"cash",
        "scheme_item_code":"acrylic-crowning",
        "restricted":False,
        "prices":[
          {
            "scheme_id":"cash-acrylic-crowning",
            "scheme_name":"cash",
            "standard":50000
          }
        ]
      }
    ]
  },
  {
    "service_id":"removable-denture",
    "name":"removable denture",
    "alternative_name":None,
    "type":"procedure",
    "schemes":[
      {
        "service_id":"removable-denture",
        "scheme_id":"cash-removable-denture",
        "scheme_name":"cash",
        "scheme_item_code":"removable-denture",
        "restricted":False,
        "prices":[
          {
            "scheme_id":"cash-removable-denture",
            "scheme_name":"cash",
            "standard":30000
          }
        ]
      },
      {
        "service_id":"removable-denture",
        "scheme_id":"nhif-removable-denture",
        "scheme_name":"nhif",
        "scheme_item_code":"6424",
        "restricted":False,
        "prices":[
          {
            "scheme_id":"nhif-removable-denture",
            "scheme_name":"nhif",
            "standard":25000
          }
        ]
      }
    ]
  },
  {
    "service_id":"dental-scaling",
    "name":"scaling and root planning",
    "alternative_name":"deep cleaning",
    "type":"procedure",
    "schemes":[
      {
        "service_id":"dental-scaling",
        "scheme_id":"cash-dental-scaling",
        "scheme_name":"cash",
        "scheme_item_code":"dental-scaling",
        "restricted":False,
        "prices":[
          {
            "scheme_id":"cash-dental-scaling",
            "scheme_name":"cash",
            "standard":30000
          }
        ]
      }
    ]
  },
  {
    "service_id":"root-canal",
    "name":"root canal treatment",
    "alternative_name":None,
    "type":"procedure",
    "schemes":[
      {
        "service_id":"root-canal",
        "scheme_id":"cash-root-canal",
        "scheme_name":"cash",
        "scheme_item_code":"root-canal",
        "restricted":False,
        "prices":[
          {
            "scheme_id":"cash-root-canal",
            "scheme_name":"cash",
            "standard":50000
          }
        ]
      }
    ]
  },
  {
    "service_id":"dental-bridge",
    "name":"dental bridge",
    "alternative_name":None,
    "type":"procedure",
    "schemes":[
      {
        "service_id":"dental-bridge",
        "scheme_id":"cash-dental-bridge",
        "scheme_name":"cash",
        "scheme_item_code":"dental-bridge",
        "restricted":False,
        "prices":[
          {
            "scheme_id":"cash-dental-bridge",
            "scheme_name":"cash",
            "price_range":True,
            "min":70000,
            "max":230000
          }
        ]
      }
    ]
  },
  {
    "service_id":"xray-periapical",
    "name":"periapical x ray",
    "alternative_name":None,
    "type":"imaging",
    "schemes":[
      {
        "service_id":"xray-periapical",
        "scheme_id":"cash-xray-periapical",
        "scheme_name":"cash",
        "scheme_item_code":"xray-periapical",
        "restricted":False,
        "prices":[
          {
            "scheme_id":"cash-xray-periapical",
            "scheme_name":"cash",
            "standard":10000
          }
        ]
      },
      {
        "service_id":"xray-periapical",
        "scheme_id":"nhif-xray-periapical",
        "scheme_name":"nhif",
        "scheme_item_code":"5295",
        "restricted":False,
        "prices":[
          {
            "scheme_id":"nhif-xray-periapical",
            "scheme_name":"nhif",
            "standard":15000
          }
        ]
      }
    ]
  },
  {
    "service_id":"xray-opg",
    "name":"orthopantomography (opg)",
    "alternative_name":"panoramic dental x ray",
    "type":"imaging",
    "schemes":[
      {
        "service_id":"xray-opg",
        "scheme_id":"cash-xray-opg",
        "scheme_name":"cash",
        "scheme_item_code":"xray-opg",
        "restricted":False,
        "prices":[
          {
            "scheme_id":"cash-xray-opg",
            "scheme_name":"cash",
            "standard":30000
          }
        ]
      },
      {
        "service_id":"xray-opg",
        "scheme_id":"nhif-xray-opg",
        "scheme_name":"nhif",
        "scheme_item_code":"5293",
        "restricted":False,
        "prices":[
          {
            "scheme_id":"nhif-xray-opg",
            "scheme_name":"nhif",
            "standard":16000
          }
        ]
      }
    ]
  },
  {
    "service_id":"xray-bitewing",
    "name":"bitewing x ray",
    "alternative_name":None,
    "type":"imaging",
    "schemes":[
      {
        "service_id":"xray-bitewing",
        "scheme_id":"cash-xray-bitewing",
        "scheme_name":"cash",
        "scheme_item_code":"xray-bitewing",
        "restricted":False,
        "prices":[
          {
            "scheme_id":"cash-xray-bitewing",
            "scheme_name":"cash",
            "standard":25000
          }
        ]
      },
      {
        "service_id":"xray-bitewing",
        "scheme_id":"nhif-xray-bitewing",
        "scheme_name":"nhif",
        "scheme_item_code":"5290",
        "restricted":False,
        "prices":[
          {
            "scheme_id":"nhif-xray-bitewing",
            "scheme_name":"nhif",
            "standard":16000
          }
        ]
      }
    ]
  },
  {
    "service_id":"xray-occlusal",
    "name":"occlusal x ray",
    "alternative_name":None,
    "type":"imaging",
    "schemes":[
      {
        "service_id":"xray-occlusal",
        "scheme_id":"cash-xray-occlusal",
        "scheme_name":"cash",
        "scheme_item_code":"xray-occlusal",
        "restricted":False,
        "prices":[
          {
            "scheme_id":"cash-xray-occlusal",
            "scheme_name":"cash",
            "standard":15000
          }
        ]
      },
      {
        "service_id":"xray-occlusal",
        "scheme_id":"nhif-xray-occlusal",
        "scheme_name":"nhif",
        "scheme_item_code":"5292",
        "restricted":False,
        "prices":[
          {
            "scheme_id":"nhif-xray-occlusal",
            "scheme_name":"nhif",
            "standard":16000
          }
        ]
      }
    ]
  },
]

users = [
  {
    "username":"nexasoft",
    "title":"master",
    "qualification":"hims",
    "designation":"hims",
    "first_name":None,
    "middle_name":None,
    "last_name":None,
    "birthdate":date.fromisoformat("2025-03-03"),
    "gender":None,
    "password":"n3x@s0ft",
    "roles":["director","admin","super"]
  },
  {
    "username":"doctor",
    "title":"dr",
    "qualification":"dds",
    "designation":"dds",
    "first_name":"dokta",
    "middle_name":"dokta",
    "last_name":"dokta",
    "birthdate":date.fromisoformat("1995-10-06"),
    "gender":None,
    "password":"1234",
    "roles":["doctor"]
  },
  {
    "username":"nurse",
    "title":"ms",
    "qualification":"dds",
    "designation":"dds",
    "first_name":"nesi",
    "middle_name":"nesi",
    "last_name":"nesi",
    "birthdate":date.fromisoformat("1995-10-06"),
    "gender":None,
    "password":"1234",
    "roles":["nurse"]
  },
  {
    "username":"receptionist",
    "title":"mr",
    "qualification":"dds",
    "designation":"dds",
    "first_name":"dokta",
    "middle_name":"dokta",
    "last_name":"dokta",
    "birthdate":date.fromisoformat("1995-10-06"),
    "gender":"male",
    "password":"1234",
    "roles":["receptionist"]
  },
  {
    "username":"kimei01",
    "title":"dr",
    "qualification":"nta 8:degree of dental surgery",
    "designation":"dds",
    "first_name":"elisante",
    "middle_name":"ndesanjo",
    "last_name":"kimei",
    "birthdate":date.fromisoformat("2025-03-03"),
    "gender":"male",
    "password":"kimei01",
    "roles":["doctor","director"]
  },
]

medicines = [
  {
    "requisition_id":f"req{datetime.now().strftime('%y%m')}r1",
    "medicine_id":"ibf200tab",
    "requisition_medicine_id":f"ibf200tabreq{datetime.now().strftime('%y%m')}r1",
    "name":"ibuprofen 200mg tab",
    "type":"analgesic",
    "category":"medicine",
    "drug_class":"nsaid",
    "fda_pregnancy_category_1":"b",
    "fda_pregnancy_category_2":"b",
    "fda_pregnancy_category_3":"d",
    "prescribable":True,
    "prescription_level":"a",
    "cancelled":False,
    "cancelled_by":None,
    "cancelled_on":None,
    "ordered":False,
    "ordered_on":None,
    "ordered_by":None,
    "order_unit":"tablet",
    "order_unit_size":100,
    "ordered_amount":0,
    "unit_price":0,
    "ordered_price":0,
    "brand_name":None,
    "manufacturer":None,
    "batch_no":None,
    "mfg_date":None,
    "expire_date":None,
    "received":True,
    "received_amount":0,
    "received_price":0,
    "received_by":None,
    "received_on":None,
    "rejected":False,
    "rejected_amount":0,
    "rejected_price":0,
    "count_unit":"tablet",
    "initial_store_balance":0,
    "schemes":[
      {
        "medicine_id":"ibf200tab",
        "scheme_name":"cash",
        "scheme_item_code":"ibf200tab",
        "restricted":False,
        "prices":[
          {
            "scheme_name":"cash",
            "standard":90
          }
        ]
      },
            {
        "medicine_id":"ibf200tab",
        "scheme_name":"nhif",
        "scheme_item_code":"11014",
        "restricted":False,
        "prices":[
          {
            "scheme_name":"nhif",
            "standard":31
          }
        ]
      }
    ],
    "store_balance":0,
    "dispensing":True,
    "dispensing_balance":0,
    "physical_count":0,
    "amc":0
  },
  {
    "requisition_id":f"req{datetime.now().strftime('%y%m')}r1",
    "medicine_id":f"ampclx500cap",
    "requisition_medicine_id":f"ampclx500capreq{datetime.now().strftime('%y%m')}r1",
    "name":"ampicillin + cloxacillin 500mg cap",
    "type":"antibiotic",
    "category":"medicine",
    "drug_class":"penicillin",
    "fda_pregnancy_category_1":"b",
    "fda_pregnancy_category_2":"b",
    "fda_pregnancy_category_3":"b",
    "prescribable":True,
    "prescription_level":"b",
    "cancelled":False,
    "cancelled_by":None,
    "cancelled_on":None,
    "ordered":False,
    "ordered_on":None,
    "ordered_by":None,
    "order_unit":"capsule",
    "order_unit_size":100,
    "ordered_amount":0,
    "unit_price":0,
    "ordered_price":0,
    "brand_name":None,
    "manufacturer":None,
    "batch_no":None,
    "mfg_date":None,
    "expire_date":None,
    "received":True,
    "received_amount":0,
    "received_price":0,
    "received_by":None,
    "received_on":None,
    "rejected":False,
    "rejected_amount":0,
    "rejected_price":0,
    "count_unit":"capsule",
    "initial_store_balance":0,
    "schemes":[
      {
        "medicine_id":"ampclx500cap",
        "scheme_name":"cash",
        "scheme_item_code":"ampclx500cap",
        "restricted":False,
        "prices":[
          {
            "scheme_name":"cash",
            "standard":200
          }
        ]
      },
      {
        "medicine_id":"ampclx500cap",
        "scheme_name":"nhif",
        "scheme_item_code":"11113",
        "restricted":False,
        "prices":[
          {
            "scheme_name":"nhif",
            "standard":137
          }
        ]
      }
    ],
    "store_balance":0,
    "dispensing":True,
    "dispensing_balance":0,
    "physical_count":0,
    "amc":0
  },
  {
    "requisition_id":f"req{datetime.now().strftime('%y%m')}r1",
    "medicine_id":f"mtz200tab",
    "requisition_medicine_id":f"mtz200tabreq{datetime.now().strftime('%y%m')}r1",
    "name":"metronidazole 200mg tab",
    "type":"antibiotic",
    "category":"medicine",
    "drug_class":"nitroimidazole",
    "fda_pregnancy_category_1":"b",
    "fda_pregnancy_category_2":"b",
    "fda_pregnancy_category_3":"b",
    "prescribable":True,
    "prescription_level":"a",
    "cancelled":False,
    "cancelled_by":None,
    "cancelled_on":None,
    "ordered":False,
    "ordered_on":None,
    "ordered_by":None,
    "order_unit":"tablet",
    "order_unit_size":100,
    "ordered_amount":0,
    "unit_price":0,
    "ordered_price":0,
    "brand_name":None,
    "manufacturer":None,
    "batch_no":None,
    "mfg_date":None,
    "expire_date":None,
    "received":True,
    "received_amount":0,
    "received_price":0,
    "received_by":None,
    "received_on":None,
    "rejected":False,
    "rejected_amount":0,
    "rejected_price":0,
    "count_unit":"tablet",
    "initial_store_balance":0,
    "schemes":[
      {
        "medicine_id":"mtz200tab",
        "scheme_name":"cash",
        "scheme_item_code":"mtz200tab",
        "restricted":False,
        "prices":[
          {
            "scheme_name":"cash",
            "standard":100
          }
        ]
      },
      {
        "medicine_id":"mtz200tab",
        "scheme_name":"nhif",
        "scheme_item_code":"11192",
        "restricted":False,
        "prices":[
          {
            "scheme_name":"nhif",
            "standard":25
          }
        ]
      }
    ],
    "store_balance":0,
    "dispensing":True,
    "dispensing_balance":0,
    "physical_count":0,
    "amc":0
  },
  {
    "requisition_id":f"req{datetime.now().strftime('%y%m')}r1",
    "medicine_id":f"hpx3sol",
    "requisition_medicine_id":f"hpx3solreq{datetime.now().strftime('%y%m')}r1",
    "name":"hydrogen peroxide 3% 100mls sol",
    "type":"antiseptic",
    "category":"medicine",
    "drug_class":"inorganic",
    "fda_pregnancy_category_1":None,
    "fda_pregnancy_category_2":None,
    "fda_pregnancy_category_3":None,
    "prescribable":True,
    "prescription_level":"a",
    "cancelled":False,
    "cancelled_by":None,
    "cancelled_on":None,
    "ordered":False,
    "ordered_on":None,
    "ordered_by":None,
    "order_unit":"bottle",
    "order_unit_size":1,
    "ordered_amount":0,
    "unit_price":0,
    "ordered_price":0,
    "brand_name":None,
    "manufacturer":None,
    "batch_no":None,
    "mfg_date":None,
    "expire_date":None,
    "received":True,
    "received_amount":0,
    "received_price":0,
    "received_by":None,
    "received_on":None,
    "rejected":False,
    "rejected_amount":0,
    "rejected_price":0,
    "count_unit":"bottle",
    "initial_store_balance":0,
    "schemes":[
      {
        "medicine_id":"hpx3sol",
        "scheme_name":"cash",
        "scheme_item_code":"hpx3sol",
        "restricted":False,
        "prices":[
          {
            "scheme_name":"cash",
            "standard":2000
          }
        ]
      },
      {
        "medicine_id":"hpx3sol",
        "scheme_name":"nhif",
        "scheme_item_code":"11512",
        "restricted":False,
        "prices":[
          {
            "scheme_name":"nhif",
            "standard":620
          }
        ]
      }
    ],
    "store_balance":0,
    "dispensing":True,
    "dispensing_balance":0,
    "physical_count":0,
    "amc":0
  },
  {
    "requisition_id":f"req{datetime.now().strftime('%y%m')}r1",
    "medicine_id":f"amx250cap",
    "requisition_medicine_id":f"amx250capreq{datetime.now().strftime('%y%m')}r1",
    "name":"amoxicillin 250mg cap",
    "type":"antibiotic",
    "category":"medicine",
    "drug_class":"penicillin",
    "fda_pregnancy_category_1":"b",
    "fda_pregnancy_category_2":"b",
    "fda_pregnancy_category_3":"b",
    "prescribable":True,
    "prescription_level":"a",
    "cancelled":False,
    "cancelled_by":None,
    "cancelled_on":None,
    "ordered":False,
    "ordered_on":None,
    "ordered_by":None,
    "order_unit":"capsule",
    "order_unit_size":100,
    "ordered_amount":0,
    "unit_price":0,
    "ordered_price":0,
    "brand_name":None,
    "manufacturer":None,
    "batch_no":None,
    "mfg_date":None,
    "expire_date":None,
    "received":True,
    "received_amount":0,
    "received_price":0,
    "received_by":None,
    "received_on":None,
    "rejected":False,
    "rejected_amount":0,
    "rejected_price":0,
    "count_unit":"capsule",
    "initial_store_balance":0,
    "schemes":[
      {
        "medicine_id":"amx250cap",
        "scheme_name":"cash",
        "scheme_item_code":"amx250cap",
        "restricted":False,
        "prices":[
          {
            "scheme_name":"cash",
            "standard":120
          }
        ]
      },
      {
        "medicine_id":"amx250cap",
        "scheme_name":"nhif",
        "scheme_item_code":"11696",
        "restricted":False,
        "prices":[
          {
            "scheme_name":"nhif",
            "standard":57
          }
        ]
      }
    ],
    "store_balance":0,
    "dispensing":True,
    "dispensing_balance":0,
    "physical_count":0,
    "amc":0
  },
  {
    "requisition_id":f"req{datetime.now().strftime('%y%m')}r1",
    "medicine_id":f"cipro500tab",
    "requisition_medicine_id":f"cipro500tabreq{datetime.now().strftime('%y%m')}r1",
    "name":"ciprofloxacin 500mg tab",
    "type":"antibiotic",
    "category":"medicine",
    "drug_class":"floroquinolone",
    "fda_pregnancy_category_1":"c",
    "fda_pregnancy_category_2":"c",
    "fda_pregnancy_category_3":"c",
    "prescribable":True,
    "prescription_level":"a",
    "cancelled":False,
    "cancelled_by":None,
    "cancelled_on":None,
    "ordered":False,
    "ordered_on":None,
    "ordered_by":None,
    "order_unit":"tablet",
    "order_unit_size":100,
    "ordered_amount":0,
    "unit_price":0,
    "ordered_price":0,
    "brand_name":None,
    "manufacturer":None,
    "batch_no":None,
    "mfg_date":None,
    "expire_date":None,
    "received":True,
    "received_amount":0,
    "received_price":0,
    "received_by":None,
    "received_on":None,
    "rejected":False,
    "rejected_amount":0,
    "rejected_price":0,
    "count_unit":"tablet",
    "initial_store_balance":0,
    "schemes":[
      {
        "medicine_id":"cipro500tab",
        "scheme_name":"cash",
        "scheme_item_code":"cipro500tab",
        "restricted":False,
        "prices":[
          {
            "scheme_name":"cash",
            "standard":300
          }
        ]
      },
      {
        "medicine_id":"cipro500tab",
        "scheme_name":"nhif",
        "scheme_item_code":"11098",
        "restricted":False,
        "prices":[
          {
            "scheme_name":"nhif",
            "standard":82
          }
        ]
      }
    ],
    "store_balance":0,
    "dispensing":True,
    "dispensing_balance":0,
    "physical_count":0,
    "amc":0
  },
  {
    "requisition_id":f"req{datetime.now().strftime('%y%m')}r1",
    "medicine_id":f"pcm500tab",
    "requisition_medicine_id":f"pcm500tabreq{datetime.now().strftime('%y%m')}r1",
    "name":"paracetamol 500mg tab",
    "type":"analgesic",
    "category":"medicine",
    "drug_class":"phenol",
    "fda_pregnancy_category_1":"b",
    "fda_pregnancy_category_2":"b",
    "fda_pregnancy_category_3":"b",
    "prescribable":True,
    "prescription_level":"a",
    "cancelled":False,
    "cancelled_by":None,
    "cancelled_on":None,
    "ordered":False,
    "ordered_on":None,
    "ordered_by":None,
    "order_unit":"tablet",
    "order_unit_size":100,
    "ordered_amount":0,
    "unit_price":0,
    "ordered_price":0,
    "brand_name":None,
    "manufacturer":None,
    "batch_no":None,
    "mfg_date":None,
    "expire_date":None,
    "received":True,
    "received_amount":0,
    "received_price":0,
    "received_by":None,
    "received_on":None,
    "rejected":False,
    "rejected_amount":0,
    "rejected_price":0,
    "count_unit":"tablet",
    "initial_store_balance":0,
    "schemes":[
      {
        "medicine_id":"pcm500tab",
        "scheme_name":"cash",
        "scheme_item_code":"pcm500tab",
        "restricted":False,
        "prices":[
          {
            "scheme_name":"cash",
            "standard":60
          }
        ]
      },
      {
        "medicine_id":"pcm500tab",
        "scheme_name":"nhif",
        "scheme_item_code":"11024",
        "restricted":False,
        "prices":[
          {
            "scheme_name":"nhif",
            "standard":26
          }
        ]
      }
    ],
    "store_balance":0,
    "dispensing":True,
    "dispensing_balance":0,
    "physical_count":0,
    "amc":0
  },
  {
    "requisition_id":f"req{datetime.now().strftime('%y%m')}r1",
    "medicine_id":f"diclosod50tab",
    "requisition_medicine_id":f"diclosod50tabreq{datetime.now().strftime('%y%m')}r1",
    "name":"diclofenac 50mg tab",
    "type":"analgesic",
    "category":"medicine",
    "drug_class":"nsaid",
    "fda_pregnancy_category_1":"b",
    "fda_pregnancy_category_2":"b",
    "fda_pregnancy_category_3":"d",
    "prescribable":True,
    "prescription_level":"a",
    "cancelled":False,
    "cancelled_by":None,
    "cancelled_on":None,
    "ordered":False,
    "ordered_on":None,
    "ordered_by":None,
    "order_unit":"tablet",
    "order_unit_size":100,
    "ordered_amount":0,
    "unit_price":0,
    "ordered_price":0,
    "brand_name":None,
    "manufacturer":None,
    "batch_no":None,
    "mfg_date":None,
    "expire_date":None,
    "received":True,
    "received_amount":0,
    "received_price":0,
    "received_by":None,
    "received_on":None,
    "rejected":False,
    "rejected_amount":0,
    "rejected_price":0,
    "count_unit":"tablet",
    "initial_store_balance":0,
    "schemes":[
      {
        "medicine_id":"diclosod50tab",
        "scheme_name":"cash",
        "scheme_item_code":"diclosod50tab",
        "restricted":False,
        "prices":[
          {
            "scheme_name":"cash",
            "standard":200
          }
        ]
      },
      {
        "medicine_id":"diclosod50tab",
        "scheme_name":"nhif",
        "scheme_item_code":"11007",
        "restricted":False,
        "prices":[
          {
            "scheme_name":"nhif",
            "standard":20
          }
        ]
      }
    ],
    "store_balance":0,
    "dispensing":True,
    "dispensing_balance":0,
    "physical_count":0,
    "amc":0
  },
  {
    "requisition_id":f"req{datetime.now().strftime('%y%m')}r1",
    "medicine_id":f"mlx10tab",
    "requisition_medicine_id":f"mlx10tabreq{datetime.now().strftime('%y%m')}r1",
    "name":"meloxicam 10mg tab",
    "type":"analgesic",
    "category":"medicine",
    "drug_class":"nsaid",
    "fda_pregnancy_category_1":"c",
    "fda_pregnancy_category_2":"c",
    "fda_pregnancy_category_3":"d",
    "prescribable":True,
    "prescription_level":"a",
    "cancelled":False,
    "cancelled_by":None,
    "cancelled_on":None,
    "ordered":False,
    "ordered_on":None,
    "ordered_by":None,
    "order_unit":"tablet",
    "order_unit_size":100,
    "ordered_amount":0,
    "unit_price":0,
    "ordered_price":0,
    "brand_name":None,
    "manufacturer":None,
    "batch_no":None,
    "mfg_date":None,
    "expire_date":None,
    "received":True,
    "received_amount":0,
    "received_price":0,
    "received_by":None,
    "received_on":None,
    "rejected":False,
    "rejected_amount":0,
    "rejected_price":0,
    "count_unit":"tablet",
    "initial_store_balance":0,
    "schemes":[
      {
        "medicine_id":"mlx10tab",
        "scheme_name":"cash",
        "scheme_item_code":"mlx10tab",
        "restricted":False,
        "prices":[
          {
            "scheme_name":"cash",
            "standard":500
          }
        ]
      }
    ],
    "store_balance":0,
    "dispensing":True,
    "dispensing_balance":0,
    "physical_count":0,
    "amc":0
  },
  {
    "requisition_id":f"req{datetime.now().strftime('%y%m')}r1",
    "medicine_id":"povi2sol",
    "requisition_medicine_id":f"povi2solreq{datetime.now().strftime('%y%m')}r1",
    "name":"povidone-iodine 2% 100ml sol",
    "type":"antiseptic",
    "category":"medical supply",
    "drug_class":"inorganic",
    "fda_pregnancy_category_1":"b",
    "fda_pregnancy_category_2":"b",
    "fda_pregnancy_category_3":"b",
    "prescribable":False,
    "prescription_level":"a",
    "cancelled":False,
    "cancelled_by":None,
    "cancelled_on":None,
    "ordered":False,
    "ordered_on":None,
    "ordered_by":None,
    "order_unit":"bottle",
    "order_unit_size":1,
    "ordered_amount":0,
    "unit_price":0,
    "ordered_price":0,
    "brand_name":None,
    "manufacturer":None,
    "batch_no":None,
    "mfg_date":None,
    "expire_date":None,
    "received":True,
    "received_amount":0,
    "received_price":0,
    "received_by":None,
    "received_on":None,
    "rejected":False,
    "rejected_amount":0,
    "rejected_price":0,
    "count_unit":"bottle",
    "initial_store_balance":0,
    "schemes":[
      {
        "medicine_id":"povi2sol",
        "scheme_name":"cash",
        "scheme_item_code":"povi2sol",
        "restricted":False,
        "prices":[
          {
            "scheme_name":"cash",
            "standard":6000
          }
        ]
      }
    ],
    "store_balance":0,
    "dispensing":True,
    "dispensing_balance":0,
    "physical_count":0,
    "amc":0
  },
  {
    "requisition_id":f"req{datetime.now().strftime('%y%m')}r1",
    "medicine_id":"chx2sol",
    "requisition_medicine_id":f"chx2solreq{datetime.now().strftime('%y%m')}r1",
    "name":"chlorhexidine 2% 100ml sol",
    "type":"antiseptic",
    "category":"medicine",
    "drug_class":"inorganic",
    "fda_pregnancy_category_1":"b",
    "fda_pregnancy_category_2":"b",
    "fda_pregnancy_category_3":"b",
    "prescribable":True,
    "prescription_level":"b",
    "cancelled":False,
    "cancelled_by":None,
    "cancelled_on":None,
    "ordered":False,
    "ordered_on":None,
    "ordered_by":None,
    "order_unit":"bottle",
    "order_unit_size":1,
    "ordered_amount":0,
    "unit_price":0,
    "ordered_price":0,
    "brand_name":None,
    "manufacturer":None,
    "batch_no":None,
    "mfg_date":None,
    "expire_date":None,
    "received":True,
    "received_amount":0,
    "received_price":0,
    "received_by":None,
    "received_on":None,
    "rejected":False,
    "rejected_amount":0,
    "rejected_price":0,
    "count_unit":"bottle",
    "initial_store_balance":0,
    "schemes":[
      {
        "medicine_id":"chx2sol",
        "scheme_name":"cash",
        "scheme_item_code":"chx2sol",
        "restricted":False,
        "prices":[
          {
            "scheme_name":"cash",
            "standard":5000
          }
        ]
      }
    ],
    "store_balance":0,
    "dispensing":True,
    "dispensing_balance":0,
    "physical_count":0,
    "amc":0
  },
  {
    "requisition_id":f"req{datetime.now().strftime('%y%m')}r1",
     "medicine_id":f"diclo25amp",
     "requisition_medicine_id":f"diclo25ampreq{datetime.now().strftime('%y%m')}r1",
    "name":"diclofenac 25mg/ml 3ml ampoule",
    "type":"analgesic",
    "category":"medicine",
    "drug_class":"nsaid",
    "fda_pregnancy_category_1":"b",
    "fda_pregnancy_category_2":"b",
    "fda_pregnancy_category_3":"d",
    "prescribable":True,
    "prescription_level":"a",
    "cancelled":False,
    "cancelled_by":None,
    "cancelled_on":None,
    "ordered":False,
    "ordered_on":None,
    "ordered_by":None,
    "order_unit":"ampoule",
    "order_unit_size":10,
    "ordered_amount":0,
    "unit_price":0,
    "ordered_price":0,
    "brand_name":None,
    "manufacturer":None,
    "batch_no":None,
    "mfg_date":None,
    "expire_date":None,
    "received":True,
    "received_amount":0,
    "received_price":0,
    "received_by":None,
    "received_on":None,
    "rejected":False,
    "rejected_amount":0,
    "rejected_price":0,
    "count_unit":"ampoule",
    "initial_store_balance":0,
    "schemes":[
      {
        "medicine_id":"diclo25amp",
        "scheme_name":"cash",
        "scheme_item_code":"diclo25amp",
        "restricted":False,
        "prices":[
          {
            "scheme_name":"cash",
            "standard":3000
          }
        ]
      },
      {
        "medicine_id":"diclo25amp",
        "scheme_name":"nhif",
        "scheme_item_code":"11006",
        "restricted":False,
        "prices":[
          {
            "scheme_name":"nhif",
            "standard":195
          }
        ]
      }
    ],
    "store_balance":0,
    "dispensing":True,
    "dispensing_balance":0,
    "physical_count":0,
    "amc":0
  },
  {
    "requisition_id":f"req{datetime.now().strftime('%y%m')}r1",
    "medicine_id":f"mtz500sol",
    "requisition_medicine_id":f"mtz500solreq{datetime.now().strftime('%y%m')}r1",
    "name":"metronidazole 5mg/ml 100ml sol",
    "type":"antibiotic",
    "category":"medicine",
    "drug_class":"nitroimidazole",
    "fda_pregnancy_category_1":"b",
    "fda_pregnancy_category_2":"b",
    "fda_pregnancy_category_3":"b",
    "prescribable":False,
    "prescription_level":"a",
    "cancelled":False,
    "cancelled_by":None,
    "cancelled_on":None,
    "ordered":False,
    "ordered_on":None,
    "ordered_by":None,
    "order_unit":"bottle",
    "order_unit_size":1,
    "ordered_amount":0,
    "unit_price":0,
    "ordered_price":0,
    "brand_name":None,
    "manufacturer":None,
    "batch_no":None,
    "mfg_date":None,
    "expire_date":None,
    "received":True,
    "received_amount":0,
    "received_price":0,
    "received_by":None,
    "received_on":None,
    "rejected":False,
    "rejected_amount":0,
    "rejected_price":0,
    "count_unit":"bottle",
    "initial_store_balance":0,
    "schemes":[
      {
        "medicine_id":"mtz500sol",
        "scheme_name":"cash",
        "scheme_item_code":"mtz500sol",
        "restricted":False,
        "prices":[
          {
            "scheme_name":"cash",
            "standard":4500
          }
        ]
      },
      {
        "medicine_id":"mtz500sol",
        "scheme_name":"nhif",
        "scheme_item_code":"11190",
        "restricted":False,
        "prices":[
          {
            "scheme_name":"nhif",
            "standard":715
          }
        ]
      }
    ],
    "store_balance":0,
    "dispensing":True,
    "dispensing_balance":0,
    "physical_count":0,
    "amc":0
  },
  {
    "requisition_id":f"req{datetime.now().strftime('%y%m')}r1",
    "medicine_id":f"dental-floss",
    "requisition_medicine_id":f"flossreq{datetime.now().strftime('%y%m')}r1",
    "name":"dental floss pack",
    "type":"accessory",
    "category":"medical supply",
    "drug_class":None,
    "fda_pregnancy_category_1":None,
    "fda_pregnancy_category_2":None,
    "fda_pregnancy_category_3":None,
    "prescribable":True,
    "prescription_level":None,
    "cancelled":False,
    "cancelled_by":None,
    "cancelled_on":None,
    "ordered":False,
    "ordered_on":None,
    "ordered_by":None,
    "order_unit":"pack",
    "order_unit_size":1,
    "ordered_amount":0,
    "unit_price":0,
    "ordered_price":0,
    "brand_name":None,
    "manufacturer":None,
    "batch_no":None,
    "mfg_date":None,
    "expire_date":None,
    "received":True,
    "received_amount":0,
    "received_price":0,
    "received_by":None,
    "received_on":None,
    "rejected":False,
    "rejected_amount":0,
    "rejected_price":0,
    "count_unit":"pack",
    "initial_store_balance":0,
    "schemes":[
      {
        "medicine_id":"dental-floss",
        "scheme_name":"cash",
        "scheme_item_code":"dental-floss",
        "restricted":False,
        "prices":[
          {
            "scheme_name":"cash",
            "standard":5000
          }
        ]
      }
    ],
    "store_balance":0,
    "dispensing":True,
    "dispensing_balance":0,
    "physical_count":0,
    "amc":0
  },
  {
    "requisition_id":f"req{datetime.now().strftime('%y%m')}r1",
    "medicine_id":f"senso-tpaste",
    "requisition_medicine_id":f"sensoreq{datetime.now().strftime('%y%m')}r1",
    "name":"sensodyne toothpaste",
    "type":"antiseptic",
    "category":"medical supply",
    "drug_class":"inorganic",
    "fda_pregnancy_category_1":None,
    "fda_pregnancy_category_2":None,
    "fda_pregnancy_category_3":None,
    "prescribable":True,
    "prescription_level":None,
    "cancelled":False,
    "cancelled_by":None,
    "cancelled_on":None,
    "ordered":False,
    "ordered_on":None,
    "ordered_by":None,
    "order_unit":"tube",
    "order_unit_size":1,
    "ordered_amount":0,
    "unit_price":0,
    "ordered_price":0,
    "brand_name":None,
    "manufacturer":None,
    "batch_no":None,
    "mfg_date":None,
    "expire_date":None,
    "received":True,
    "received_amount":0,
    "received_price":0,
    "received_by":None,
    "received_on":None,
    "rejected":False,
    "rejected_amount":0,
    "rejected_price":0,
    "count_unit":"tube",
    "initial_store_balance":0,
    "schemes":[
      {
        "medicine_id":"senso-tpaste",
        "scheme_name":"cash",
        "scheme_item_code":"senso-tpaste",
        "restricted":False,
        "prices":[
          {
            "scheme_name":"cash",
            "standard":9000
          }
        ]
      }
    ],
    "store_balance":0,
    "dispensing":True,
    "dispensing_balance":0,
    "physical_count":0,
    "amc":0
  },
  {
    "requisition_id":f"req{datetime.now().strftime('%y%m')}r1",
    "medicine_id":f"tbrush-softs",
    "requisition_medicine_id":f"tbrushreq{datetime.now().strftime('%y%m')}r1",
    "name":"toothbrush softs",
    "type":"accessory",
    "category":"medical supply",
    "drug_class":None,
    "fda_pregnancy_category_1":None,
    "fda_pregnancy_category_2":None,
    "fda_pregnancy_category_3":None,
    "prescribable":True,
    "prescription_level":None,
    "cancelled":False,
    "cancelled_by":None,
    "cancelled_on":None,
    "ordered":False,
    "ordered_on":None,
    "ordered_by":None,
    "order_unit":"tube",
    "order_unit_size":1,
    "ordered_amount":0,
    "unit_price":0,
    "ordered_price":0,
    "brand_name":None,
    "manufacturer":None,
    "batch_no":None,
    "mfg_date":None,
    "expire_date":None,
    "received":True,
    "received_amount":0,
    "received_price":0,
    "received_by":None,
    "received_on":None,
    "rejected":False,
    "rejected_amount":0,
    "rejected_price":0,
    "count_unit":"tube",
    "initial_store_balance":0,
    "schemes":[
      {
        "medicine_id":"tbrush-softs",
        "scheme_name":"cash",
        "scheme_item_code":"tbrush-softs",
        "restricted":False,
        "prices":[
          {
            "scheme_name":"cash",
            "standard":2000
          }
        ]
      }
    ],
    "store_balance":0,
    "dispensing":True,
    "dispensing_balance":0,
    "physical_count":0,
    "amc":0
  },
  {
    "requisition_id":f"req{datetime.now().strftime('%y%m')}r1",
    "medicine_id":f"floride-tpaste",
    "requisition_medicine_id":f"florireq{datetime.now().strftime('%y%m')}r1",
    "name":"fluoridated toothpaste",
    "type":"antiseptic",
    "category":"medical supply",
    "drug_class":"inorganic",
    "fda_pregnancy_category_1":None,
    "fda_pregnancy_category_2":None,
    "fda_pregnancy_category_3":None,
    "prescribable":True,
    "prescription_level":None,
    "cancelled":False,
    "cancelled_by":None,
    "cancelled_on":None,
    "ordered":False,
    "ordered_on":None,
    "ordered_by":None,
    "order_unit":"tube",
    "order_unit_size":1,
    "ordered_amount":0,
    "unit_price":0,
    "ordered_price":0,
    "brand_name":None,
    "manufacturer":None,
    "batch_no":None,
    "mfg_date":None,
    "expire_date":None,
    "received":True,
    "received_amount":0,
    "received_price":0,
    "received_by":None,
    "received_on":None,
    "rejected":False,
    "rejected_amount":0,
    "rejected_price":0,
    "count_unit":"tube",
    "initial_store_balance":0,
    "schemes":[
      {
        "medicine_id":"floride-tpaste",
        "scheme_name":"cash",
        "scheme_item_code":"floride-tpaste",
        "restricted":False,
        "prices":[
          {
            "scheme_name":"cash",
            "standard":4500
          }
        ]
      },
    ],
    "store_balance":0,
    "dispensing":True,
    "dispensing_balance":0,
    "physical_count":0,
    "amc":0
  },
  {
    "requisition_id":f"req{datetime.now().strftime('%y%m')}r1",
    "medicine_id":f"nystsusp",
    "requisition_medicine_id":f"nystsuspreq{datetime.now().strftime('%y%m')}r1",
    "name":"nystatin suspension",
    "type":"antifungal",
    "category":"medicine",
    "drug_class":"polyene",
    "fda_pregnancy_category_1":"c",
    "fda_pregnancy_category_2":"c",
    "fda_pregnancy_category_3":"c",
    "prescribable":True,
    "prescription_level":"a",
    "cancelled":False,
    "cancelled_by":None,
    "cancelled_on":None,
    "ordered":False,
    "ordered_on":None,
    "ordered_by":None,
    "order_unit":"bottle",
    "order_unit_size":1,
    "ordered_amount":0,
    "unit_price":0,
    "ordered_price":0,
    "brand_name":None,
    "manufacturer":None,
    "batch_no":None,
    "mfg_date":None,
    "expire_date":None,
    "received":True,
    "received_amount":0,
    "received_price":0,
    "received_by":None,
    "received_on":None,
    "rejected":False,
    "rejected_amount":0,
    "rejected_price":0,
    "count_unit":"bottle",
    "initial_store_balance":0,
    "schemes":[
      {
        "medicine_id":"nystsusp",
        "scheme_name":"cash",
        "scheme_item_code":"nystsusp",
        "restricted":False,
        "prices":[
          {
            "scheme_name":"cash",
            "standard":5000
          }
        ]
      },
      {
        "medicine_id":"nystsusp",
        "scheme_name":"nhif",
        "scheme_item_code":"11183",
        "restricted":False,
        "prices":[
          {
            "scheme_name":"nhif",
            "standard":1925
          }
        ]
      }
    ],
    "store_balance":0,
    "dispensing":True,
    "dispensing_balance":0,
    "physical_count":0,
    "amc":0
  },
  {
    "requisition_id":f"req{datetime.now().strftime('%y%m')}r1",
    "medicine_id":f"diclo20gel",
    "requisition_medicine_id":f"diclo20gelreq{datetime.now().strftime('%y%m')}r1",
    "name":"diclofenac 20g gel",
    "type":"analgesic",
    "category":"medicine",
    "drug_class":"nsaid",
    "fda_pregnancy_category_1":"c",
    "fda_pregnancy_category_2":"c",
    "fda_pregnancy_category_3":"d",
    "prescribable":True,
    "prescription_level":"a",
    "cancelled":False,
    "cancelled_by":None,
    "cancelled_on":None,
    "ordered":False,
    "ordered_on":None,
    "ordered_by":None,
    "order_unit":"tube",
    "order_unit_size":1,
    "ordered_amount":0,
    "unit_price":0,
    "ordered_price":0,
    "brand_name":None,
    "manufacturer":None,
    "batch_no":None,
    "mfg_date":None,
    "expire_date":None,
    "received":True,
    "received_amount":0,
    "received_price":0,
    "received_by":None,
    "received_on":None,
    "rejected":False,
    "rejected_amount":0,
    "rejected_price":0,
    "count_unit":"tube",
    "initial_store_balance":0,
    "schemes":[
      {
        "medicine_id":"diclo20gel",
        "scheme_name":"cash",
        "scheme_item_code":"diclo20gel",
        "restricted":False,
        "prices":[
          {
            "scheme_name":"cash",
            "standard":5000
          }
        ]
      },
      {
        "medicine_id":"diclo20gel",
        "scheme_name":"nhif",
        "scheme_item_code":"11533",
        "restricted":False,
        "prices":[
          {
            "scheme_name":"nhif",
            "standard":1853
          }
        ]
      }
    ],
    "store_balance":0,
    "dispensing":True,
    "dispensing_balance":0,
    "physical_count":0,
    "amc":0
  }
]

requisition = {
  "requisition_id":f"req{datetime.now().strftime('%y%m')}r1",
  "initiated":True,
  "vendor":"nexasoft",
  "initiated_by":"nexasoft",
  "placed":True,
  "ordered_by":"nexasoft",
  "received":True,
  "received_by":"nexasoft",
  "invoice_id":"inv000",
  "delivery_note_id":"dn000"
}

















































