"""A module to store initial values for various database models in the app"""
#IMPORTS
from datetime import datetime,date,timedelta

payment_schemes = [
  {
    "name":"cash",
    "apis":[],
    "pricing":{"price_range":False,"copayment":False,"min":0,"max":0,"topup":0,"standard":200,"priority":500}
  },
  {
    "name":"nhif",
    "apis":[],
    "pricing":{"price_range":False,"copayment":False,"min":0,"max":0,"topup":0,"standard":200,"priority":500}
  },
  {
    "name":"jubilee",
    "apis":[],
    "pricing":{"price_range":False,"copayment":False,"min":0,"max":0,"topup":0,"standard":200,"priority":500}
  },
  {
    "name":"assemble",
    "apis":[],
    "pricing":{"price_range":False,"copayment":False,"min":0,"max":0,"topup":0,"standard":200,"priority":500}
  },
  {
    "name":"britam",
    "apis":[],
    "pricing":{"price_range":False,"copayment":False,"min":0,"max":0,"topup":0,"standard":200,"priority":500}
  },
  {
    "name":"strategis",
    "apis":[],
    "pricing":{"price_range":False,"copayment":False,"min":0,"max":0,"topup":0,"standard":200,"priority":500}
  }
]

###
facility = {
  "facility_id":f"dental-futuresmile",          #
  "name":"future smile specialized dental clinic",
  "short_name":"future dental clinic",
  "tag":"ftr",
  "postcode":67102,
  "category":"dental",
  "level":"clinic",
  "certifications":["NTA 4:Basic Technician Certificate","NTA 5:Technician Certificate","NTA 6:Ordinary Diploma","NTA 7:Higher Diploma","NTA 8:Bachelor's Degree","NTA 9:Master's Degree","NTA 10:Doctorate Degree"],
  "designations":["MDent","DDS","ADO","DT","Pharm Tech","Pharmacist","Medical Doctor","Receptionist","Radiographer","Radiologist","Registered Nurse","Enrolled Nurse","Medical Attendant","Laboratory Technician"],
  "primary_roles":["Doctor","Nurse","Receptionist","Radiographer","Office Cleaner"],
  "secondary_roles":[None,"Director"],
  "services":["Consultation","Imaging","Procedure","Surgery"],
  "medicine_types":["Antibiotic","Analgesic","Antiseptic","Antifungal","Accessory"],
  "vendors":[],
  "mos":[2,4],
  "occupations":["Business","Child","Student","Housewife","Farmer","Transportation","Restaurant","Reception","Cashier","Doctor","Nurse","Pharmacist","Laboratory Technician","Dentist","Physiotherap","Banker","Manager","Director","Accountant","Teacher","Lecturer","Headmaster","Headmistress","Police","Human Resource Officer","Software Developer","IT Officer"],
  "years_of_existence":[datetime.now().year],
}

default_subscription = {
  "facility_id":"dental-futuresmile",
  "receipt":"trial001",
  "tier":"standard",
  "cost":0,"paid_amount":0,"pending_amount":0,"end_time":datetime.now() + timedelta(days=30)
}

#DEPARTMENTS
departments = [
  {
    "department_id":"opd",
    "facility_id":"dental-futuresmile",
    "name":"outpatient",
    "display_icon":"fa-solid fa-hospital",
    "clinical":True,
    "sections":[
      {
        "section_id":"opd-reception",
        "department_id":"opd",
        "name":"reception",
        "display_icon":"fa-solid fa-id-card-clip"
      },
      {
        "section_id":"opd-triage",
        "department_id":"opd",
        "name":"triage",
        "display_icon":"fa-solid fa-heart-pulse"
      },
      {
        "section_id":"opd-consults",
        "department_id":"opd",
        "name":"consultations",
        "display_icon":"fa-solid fa-stethoscope",
        "rooms":[
          {
            "room_id":"consult-1",
            "section_id":"opd-consults",
            "room_no":1,
            "name":None,
            "for_priority_clients":True
          },
          {
            "room_id":"consult-2",
            "section_id":"opd-consults",
            "room_no":2,
            "name":None,
            "for_priority_clients":False
          }
        ]
      },
      {
        "section_id":"opd-injections",
        "department_id":"opd",
        "name":"injections",
        "display_icon":"fa-solid fa-syringe",
      },
      {
        "section_id":"opd-observations",
        "department_id":"opd",
        "name":"observations",
        "display_icon":"fa-solid fa-bed-pulse",
        "wards":[
          {
            "ward_id":"obs-1",
            "section_id":"opd-observations",
            "ward_no":1,
            "name":"pediatric",
            "general":True
          },
          {
            "ward_id":"obs-2",
            "section_id":"opd-observations",
            "ward_no":2,
            "name":"adult",
            "general":True
          }
        ]
      }
    ]
  },
  {
    "department_id":"finances",
    "facility_id":"dental-futuresmile",
    "name":"finances",
    "display_icon":"fa-solid fa-coins",
    "clinical":True,
    "sections":[
      {
        "section_id":"finances-admin",
        "department_id":"finances",
        "name":"admin",
        "display_icon":"fa-solid fa-id-card-briefcase"
      },
      {
        "section_id":"finances-opd-billing",
        "department_id":"finances",
        "name":"opd billings",
        "display_icon":"fa-solid fa-hand-holding-collar"
      },
      {
        "section_id":"finances-revenues",
        "department_id":"finances",
        "name":"revenues",
        "display_icon":"fa-solid fa-sack-dollar"
      },
      {
        "section_id":"finances-expenditures",
        "department_id":"finances",
        "name":"expenditures",
        "display_icon":"fa-solid fa-hand-holding-collar"
      },
    ]
  },
  {
    "department_id":"lab",
    "facility_id":"dental-futuresmile",
    "name":"laboratory",
    "display_icon":"fa-solid fa-microscope",
    "clinical":True,
    "sections":[
      {
        "section_id":"lab-admin",
        "department_id":"lab",
        "name":"admin",
        "display_icon":"fa-solid fa-id-card-briefcase-medical"
      },
      {
        "section_id":"lab-reception",
        "department_id":"lab",
        "name":"reception",
        "display_icon":"fa-solid fa-id-card-clip"
      },
      {
        "section_id":"lab-phlebotomy",
        "department_id":"lab",
        "name":"phlebotomy",
        "display_icon":"fa-solid fa-droplet"
      },
      {
        "section_id":"lab-chemistry",
        "department_id":"lab",
        "name":"clinical chemistry",
        "display_icon":"fa-solid fa-flask-vial"
      },
      {
        "section_id":"lab-micro",
        "department_id":"lab",
        "name":"microbiology",
        "display_icon":"fa-solid fa-vial-virus"
      },
      {
        "section_id":"lab-para",
        "department_id":"lab",
        "name":"parasitology",
        "display_icon":"fa-solid fa-vial-virus"
      },
      {
        "section_id":"lab-hematology",
        "department_id":"lab",
        "name":"haematology",
        "display_icon":"fa-solid fa-droplet"
      },
    ]
  },
  {
    "department_id":"imagings",
    "facility_id":"dental-futuresmile",
    "name":"imagings",
    "display_icon":"fa-solid fa-x-ray",
    "clinical":True,
    "sections":[
      {
        "section_id":"imagings-admin",
        "department_id":"imagings",
        "name":"admin",
        "display_icon":"fa-solid fa-id-card-briefcase-medical"
      },
      {
        "section_id":"imagings-reception",
        "department_id":"imagings",
        "name":"reception",
        "display_icon":"fa-solid fa-id-card-clip"
      },
      {
        "section_id":"imagings-x-ray",
        "department_id":"imagings",
        "name":"x ray",
        "display_icon":"fa-solid fa-id-card-clip"
      },
      {
        "section_id":"imagings-ultrasound",
        "department_id":"imagings",
        "name":"ultrasound",
        "display_icon":"fa-solid fa-x-ray"
      },
    ]
  },
  {
    "department_id":"pharm",
    "facility_id":"dental-futuresmile",
    "name":"pharmacy",
    "display_icon":"fa-solid fa-pills",
    "clinical":True,
    "sections":[
      {
        "section_id":"pharm-admin",
        "department_id":"pharm",
        "name":"admin",
        "display_icon":"fa-solid fa-briefcase-medical"
      },
      {
        "section_id":"pharm-reception",
        "department_id":"pharm",
        "name":"reception",
        "display_icon":"fa-solid fa-id-card-clip"
      },
      {
        "section_id":"pharm-main",
        "department_id":"pharm",
        "name":"main store",
        "display_icon":"fa-solid fa-house-medical"
      },
      {
        "section_id":"pharm-opd-dispesping",
        "department_id":"pharm",
        "name":"opd dispensing",
        "display_icon":"fa-solid fa-prescription-bottle-medical"
      },
    ]
  },
  {
    "department_id":"logistics",
    "facility_id":"dental-futuresmile",
    "name":"logistics",
    "display_icon":"fa-solid fa-warehouse",
    "sections":[
      {
        "section_id":"logistics-admin",
        "department_id":"logistics",
        "name":"admin",
        "display_icon":"fa-solid fa-id-card-briefcase-medical"
      },
      {
        "section_id":"logistics-procurement",
        "department_id":"logistics",
        "name":"procurement",
        "display_icon":"fa-solid fa-hand-holding-collar"
      },
      {
        "section_id":"logistics-distribution",
        "department_id":"logistics",
        "name":"distribution",
        "display_icon":"fa-solid fa-sack-dollar"
      }
    ]
  },
]

other_services = [
  {
    "service_id":"consult-mds",
    "name":"specialist consultation",
    "alternative_name":None,
    "type":"consultation"
  },
  {
    "service_id":"dental-flossing",
    "name":"dental-flossing",
    "alternative_name":None,
    "type":"procedure"
  }
]

services = [
  {
    "service_id":"consult-dds",
    "name":"dentist consultation",
    "alternative_name":None,
    "type":"consultation",
    "schemes":[
      {
        "service_id":"consult-dds",
        "scheme_id":"cash-consult-dds",
        "scheme_name":"cash",
        "scheme_item_code":"consult-dds",
        "restricted":False,
        "prices":[
          {
            "scheme_id":"cash-consult-dds",
            "scheme_name":"cash",
            "standard":5000
          }
        ]
      },
      {
        "service_id":"consult-dds",
        "scheme_id":"nhif-consult-dds",
        "scheme_name":"nhif",
        "scheme_item_code":"10002",
        "restricted":False,
        "prices":[
          {
            "scheme_id":"nhif-consult-dds",
            "scheme_name":"nhif",
            "standard":7000
          }
        ]
      }
    ]
  },
  {
    "service_id":"extraction-permanent",
    "name":"permanent tooth extration",
    "alternative_name":None,
    "type":"procedure",
    "schemes":[
      {
        "service_id":"extraction-permanent",
        "scheme_id":"cash-extraction-permanent",
        "scheme_name":"cash",
        "scheme_item_code":"extraction-permanent",
        "restricted":False,
        "prices":[
          {
            "scheme_id":"cash-extraction-permanent",
            "scheme_name":"cash",
            "standard":15000
          }
        ]
      },
      {
        "service_id":"extraction-permanent",
        "scheme_id":"cash-extraction-permanent",
        "scheme_name":"nhif",
        "scheme_item_code":"6108",
        "restricted":False,
        "prices":[
          {
            "scheme_id":"cash-extraction-permanent",
            "scheme_name":"nhif",
            "standard":6500
          }
        ]
      }
    ]
  },
  {
    "service_id":"extraction-decidous",
    "name":"deciduous tooth extraction",
    "alternative_name":None,
    "type":"procedure",
    "schemes":[
      {
        "service_id":"extraction-decidous",
        "scheme_id":"cash-extraction-decidous",
        "scheme_name":"cash",
        "scheme_item_code":"extraction-decidous",
        "restricted":False,
        "prices":[
          {
            "scheme_id":"cash-extraction-decidous",
            "scheme_name":"cash",
            "standard":10000
          }
        ]
      },
      {
        "service_id":"extraction-decidous",
        "scheme_id":"nhif-extraction-decidous",
        "scheme_name":"nhif",
        "scheme_item_code":"6108",
        "restricted":False,
        "prices":[
          {
            "scheme_id":"nhif-extraction-decidous",
            "scheme_name":"nhif",
            "standard":5174
          }
        ]
      }
    ]
  },
  {
    "service_id":"disimpaction",
    "name":"tooth disimpaction",
    "alternative_name":"extraction of complex tooth",
    "type":"procedure",
    "schemes":[
      {
        "service_id":"disimpaction",
        "scheme_id":"cash-disimpaction",
        "scheme_name":"cash",
        "scheme_item_code":"disimpaction",
        "restricted":False,
        "prices":[
          {
            "scheme_id":"cash-disimpaction",
            "scheme_name":"disimpaction",
            "standard":35000
          }
        ]
      },
      {
        "service_id":"disimpaction",
        "scheme_id":"nhif-disimpaction",
        "scheme_name":"nhif",
        "scheme_item_code":"41041",
        "restricted":False,
        "prices":[
          {
            "scheme_id":"nhif-disimpaction",
            "scheme_name":"nhif",
            "standard":29250
          }
        ]
      }
    ]
  },
  {
    "service_id":"filling-temporary",
    "name":"temporary tooth filling",
    "alternative_name":None,
    "type":"procedure",
    "schemes":[
      {
        "service_id":"filling-temporary",
        "scheme_id":"cash-filling-temporary",
        "scheme_name":"cash",
        "scheme_item_code":"filling-temporary",
        "restricted":False,
        "prices":[
          {
            "scheme_id":"cash-filling-temporary",
            "scheme_name":"cash",
            "standard":30000
          }
        ]
      },
      {
        "service_id":"filling-temporary",
        "scheme_id":"nhif-filling-temporary",
        "scheme_name":"nhif",
        "scheme_item_code":"6517",
        "restricted":False,
        "prices":[
          {
            "scheme_id":"nhif-filling-temporary",
            "scheme_name":"nhif",
            "standard":36000
          }
        ]
      }
    ]
  },
  {
    "service_id":"filling-permanent",
    "name":"permanent tooth filling",
    "alternative_name":None,
    "type":"procedure",
    "schemes":[
      {
        "service_id":"filling-permanent",
        "scheme_id":"cash-filling-permanent",
        "scheme_name":"cash",
        "scheme_item_code":"filling-permanent",
        "restricted":False,
        "prices":[
          {
            "scheme_id":"cash-filling-permanent",
            "scheme_name":"cash",
            "standard":40000
          }
        ]
      },
      {
        "service_id":"filling-permanent",
        "scheme_id":"nhif-filling-permanent",
        "scheme_name":"nhif",
        "scheme_item_code":"6515",
        "restricted":False,
        "prices":[
          {
            "scheme_id":"nhif-filling-permanent",
            "scheme_name":"nhif",
            "standard":42120
          }
        ]
      }
    ]
  },
  {
    "service_id":"dental-splinting",
    "name":"dental splinting",
    "alternative_name":"splinting of teeh per quadrant",
    "type":"procedure",
    "schemes":[
      {
        "service_id":"dental-splinting",
        "scheme_id":"cash-dental-splinting",
        "scheme_name":"cash",
        "scheme_item_code":"dental-splinting",
        "restricted":False,
        "prices":[
          {
            "scheme_id":"cash-dental-splinting",
            "scheme_name":"cash",
            "standard":50000
          }
        ]
      },
      {
        "service_id":"dental-splinting",
        "scheme_id":"nhif-dental-splinting",
        "scheme_name":"nhif",
        "scheme_item_code":"6267",
        "restricted":False,
        "prices":[
          {
            "scheme_id":"nhif-dental-splinting",
            "scheme_name":"nhif",
            "standard":10000
          }
        ]
      }
    ]
  },
  {
    "service_id":"imf",
    "name":"intermaxillary fixation",
    "alternative_name":"fixing broken jaw",
    "type":"surgery",
    "schemes":[
      {
        "service_id":"imf",
        "scheme_id":"cash-imf",
        "scheme_name":"cash",
        "scheme_item_code":"imf",
        "restricted":False,
        "prices":[
          {
            "scheme_id":"cash-imf",
            "scheme_name":"cash",
            "standard":350000
          }
        ]
      },
      {
        "service_id":"imf",
        "scheme_id":"nhif-imf",
        "scheme_name":"nhif",
        "scheme_item_code":"41055",
        "restricted":False,
        "prices":[
          {
            "scheme_id":"nhif-imf",
            "scheme_name":"nhif",
            "standard":100000
          }
        ]
      }
    ]
  },
  {
    "service_id":"gingivaectomy",
    "name":"gingivaectomy",
    "alternative_name":None,
    "type":"procedure",
    "schemes":[
      {
        "service_id":"gingivaectomy",
        "scheme_id":"cash-gingivaectomy",
        "scheme_name":"cash",
        "scheme_item_code":"gingivaectomy",
        "restricted":False,
        "prices":[
          {
            "scheme_id":"cash-gingivaectomy",
            "scheme_name":"cash",
            "standard":40000
          }
        ]
      },
      {
        "service_id":"gingivaectomy",
        "scheme_id":"nhif-gingivaectomy",
        "scheme_name":"nhif",
        "scheme_item_code":"41047",
        "restricted":False,
        "prices":[
          {
            "scheme_id":"nhif-gingivaectomy",
            "scheme_name":"nhif",
            "standard":35000
          }
        ]
      }
    ]
  },
  {
    "service_id":"frenotomy",
    "name":"Tongue tie release",
    "alternative_name":"frenotomy",
    "type":"procedure",
    "schemes":[
      {
        "service_id":"frenotomy",
        "scheme_id":"cash-frenotomy",
        "scheme_name":"cash",
        "scheme_item_code":"frenotomy",
        "restricted":False,
        "prices":[
          {
            "scheme_id":"cash-frenotomy",
            "scheme_name":"cash",
            "standard":25000
          }
        ]
      }
    ]
  },
  {
    "service_id":"whitening",
    "name":"teeth whitening",
    "alternative_name":"bleaching",
    "type":"procedure",
    "schemes":[
      {
        "service_id":"whitening",
        "scheme_id":"cash-whitening",
        "scheme_name":"cash",
        "scheme_item_code":"whitening",
        "restricted":False,
        "prices":[
          {
            "scheme_id":"cash-whitening",
            "scheme_name":"cash",
            "standard":120000
          }
        ]
      }
    ]
  },
  {
    "service_id":"anterior-dental-filling",
    "name":"pin addition dental filling (anterior)",
    "alternative_name":"anterior pin retained filling",
    "type":"procedure",
    "schemes":[
      {
        "service_id":"anterior-dental-filling",
        "scheme_id":"cash-anterior-dental-filling",
        "scheme_name":"cash",
        "scheme_item_code":"anterior-dental-filling",
        "restricted":False,
        "prices":[
          {
            "scheme_id":"cash-anterior-dental-filling",
            "scheme_name":"cash",
            "standard":50000
          }
        ]
      },
      {
        "service_id":"anterior-dental-filling",
        "scheme_id":"nhif-anterior-dental-filling",
        "scheme_name":"nhif",
        "scheme_item_code":"6518",
        "restricted":False,
        "prices":[
          {
            "scheme_id":"nhif-anterior-dental-filling",
            "scheme_name":"nhif",
            "standard":50000
          }
        ]
      }
    ]
  },
  {
    "service_id":"posterior-dental-filling",
    "name":"pin addition dental filling (posterior)",
    "alternative_name":"posterior pin retained filling",
    "type":"procedure",
    "schemes":[
      {
        "service_id":"posterior-dental-filling",
        "scheme_id":"cash-posterior-dental-filling",
        "scheme_name":"cash",
        "scheme_item_code":"posterior-dental-filling",
        "restricted":False,
        "prices":[
          {
            "scheme_id":"cash-posterior-dental-filling",
            "scheme_name":"cash",
            "standard":50000
          }
        ]
      },
      {
        "service_id":"posterior-dental-filling",
        "scheme_id":"nhif-posterior-dental-filling",
        "scheme_name":"nhif",
        "scheme_item_code":"6411",
        "restricted":False,
        "prices":[
          {
            "scheme_id":"nhif-posterior-dental-filling",
            "scheme_name":"nhif",
            "standard":60000
          }
        ]
      }
    ]
  },
  {
    "service_id":"braces",
    "name":"orthodontic braces",
    "alternative_name":"fixed orthodontic appliance fixing per jaw",
    "type":"procedure",
    "schemes":[
      {
        "service_id":"braces",
        "scheme_id":"cash-braces",
        "scheme_name":"cash",
        "scheme_item_code":"braces",
        "restricted":False,
        "prices":[
          {
            "scheme_id":"cash-braces",
            "scheme_name":"cash",
            "standard":600000
          }
        ]
      },
      {
        "service_id":"braces",
        "scheme_id":"nhif-braces",
        "scheme_name":"nhif",
        "scheme_item_code":"6522",
        "restricted":False,
        "prices":[
          {
            "scheme_id":"nhif-braces",
            "scheme_name":"nhif",
            "copayment":True,
            "standard":275000,
            "topup":325000
          }
        ]
      }
    ]
  },
  {
    "service_id":"dental-stones",
    "name":"dental stones/jewelry",
    "alternative_name":None,
    "type":"procedure",
    "schemes":[
      {
        "service_id":"dental-stones",
        "scheme_id":"cash-dental-stones",
        "scheme_name":"cash",
        "scheme_item_code":"dental-stones",
        "restricted":False,
        "prices":[
          {
            "scheme_id":"cash-dental-stones",
            "scheme_name":"cash",
            "standard":15000
          }
        ]
      }
    ]
  },
  {
    "service_id":"dental-flap",
    "name":"dental flap excision",
    "alternative_name":None,
    "type":"procedure",
    "schemes":[
      {
        "service_id":"dental-flap",
        "scheme_id":"cash-dental-flap",
        "scheme_name":"cash",
        "scheme_item_code":"dental-flap",
        "restricted":False,
        "prices":[
          {
            "scheme_id":"cash-dental-flap",
            "scheme_name":"cash",
            "standard":25000
          }
        ]
      },
      {
        "service_id":"dental-flap",
        "scheme_id":"nhif-dental-flap",
        "scheme_name":"nhif",
        "scheme_item_code":"41046",
        "restricted":False,
        "prices":[
          {
            "scheme_id":"nhif-dental-flap",
            "scheme_name":"nhif",
            "standard":35000
          }
        ]
      }
    ]
  },
  {
    "service_id":"veneer",
    "name":"dental veneer",
    "alternative_name":"tooth veneer",
    "type":"procedure",
    "schemes":[
      {
        "service_id":"veneer",
        "scheme_id":"cash-veneer",
        "scheme_name":"cash",
        "scheme_item_code":"veneer",
        "restricted":False,
        "prices":[
          {
            "scheme_id":"cash-veneer",
            "scheme_name":"cash",
            "standard":30000
          }
        ]
      }
    ]
  },
  {
    "service_id":"ceramic-crowning",
    "name":"ceramic dental crowning",
    "alternative_name":None,
    "type":"procedure",
    "schemes":[
      {
        "service_id":"ceramic-crowning",
        "scheme_id":"cash-ceramic-crowning",
        "scheme_name":"cash",
        "scheme_item_code":"ceramic-crowning",
        "restricted":False,
        "prices":[
          {
            "scheme_id":"cash-ceramic-crowning",
            "scheme_name":"cash",
            "standard":250000
          }
        ]
      }
    ]
  },
  {
    "service_id":"acrylic-crowning",
    "name":"acrylic dental crowning",
    "alternative_name":None,
    "type":"procedure",
    "schemes":[
      {
        "service_id":"acrylic-crowning",
        "scheme_id":"cash-acrylic-crowning",
        "scheme_name":"cash",
        "scheme_item_code":"acrylic-crowning",
        "restricted":False,
        "prices":[
          {
            "scheme_id":"cash-acrylic-crowning",
            "scheme_name":"cash",
            "standard":50000
          }
        ]
      }
    ]
  },
  {
    "service_id":"removable-denture",
    "name":"removable denture",
    "alternative_name":None,
    "type":"procedure",
    "schemes":[
      {
        "service_id":"removable-denture",
        "scheme_id":"cash-removable-denture",
        "scheme_name":"cash",
        "scheme_item_code":"removable-denture",
        "restricted":False,
        "prices":[
          {
            "scheme_id":"cash-removable-denture",
            "scheme_name":"cash",
            "standard":30000
          }
        ]
      },
      {
        "service_id":"removable-denture",
        "scheme_id":"nhif-removable-denture",
        "scheme_name":"nhif",
        "scheme_item_code":"6424",
        "restricted":False,
        "prices":[
          {
            "scheme_id":"nhif-removable-denture",
            "scheme_name":"nhif",
            "standard":25000
          }
        ]
      }
    ]
  },
  {
    "service_id":"dental-scaling",
    "name":"scaling and root planning",
    "alternative_name":"deep cleaning",
    "type":"procedure",
    "schemes":[
      {
        "service_id":"dental-scaling",
        "scheme_id":"cash-dental-scaling",
        "scheme_name":"cash",
        "scheme_item_code":"dental-scaling",
        "restricted":False,
        "prices":[
          {
            "scheme_id":"cash-dental-scaling",
            "scheme_name":"cash",
            "standard":30000
          }
        ]
      }
    ]
  },
  {
    "service_id":"root-canal",
    "name":"root canal treatment",
    "alternative_name":None,
    "type":"procedure",
    "schemes":[
      {
        "service_id":"root-canal",
        "scheme_id":"cash-root-canal",
        "scheme_name":"cash",
        "scheme_item_code":"root-canal",
        "restricted":False,
        "prices":[
          {
            "scheme_id":"cash-root-canal",
            "scheme_name":"cash",
            "standard":50000
          }
        ]
      }
    ]
  },
  {
    "service_id":"dental-bridge",
    "name":"dental bridge",
    "alternative_name":None,
    "type":"procedure",
    "schemes":[
      {
        "service_id":"dental-bridge",
        "scheme_id":"cash-dental-bridge",
        "scheme_name":"cash",
        "scheme_item_code":"dental-bridge",
        "restricted":False,
        "prices":[
          {
            "scheme_id":"cash-dental-bridge",
            "scheme_name":"cash",
            "price_range":True,
            "min":70000,
            "max":230000
          }
        ]
      }
    ]
  },
  {
    "service_id":"xray-periapical",
    "name":"periapical x ray",
    "alternative_name":None,
    "type":"imaging",
    "schemes":[
      {
        "service_id":"xray-periapical",
        "scheme_id":"cash-xray-periapical",
        "scheme_name":"cash",
        "scheme_item_code":"xray-periapical",
        "restricted":False,
        "prices":[
          {
            "scheme_id":"cash-xray-periapical",
            "scheme_name":"cash",
            "standard":10000
          }
        ]
      },
      {
        "service_id":"xray-periapical",
        "scheme_id":"nhif-xray-periapical",
        "scheme_name":"nhif",
        "scheme_item_code":"5295",
        "restricted":False,
        "prices":[
          {
            "scheme_id":"nhif-xray-periapical",
            "scheme_name":"nhif",
            "standard":15000
          }
        ]
      }
    ]
  },
  {
    "service_id":"xray-opg",
    "name":"orthopantomography (opg)",
    "alternative_name":"panoramic dental x ray",
    "type":"imaging",
    "schemes":[
      {
        "service_id":"xray-opg",
        "scheme_id":"cash-xray-opg",
        "scheme_name":"cash",
        "scheme_item_code":"xray-opg",
        "restricted":False,
        "prices":[
          {
            "scheme_id":"cash-xray-opg",
            "scheme_name":"cash",
            "standard":30000
          }
        ]
      },
      {
        "service_id":"xray-opg",
        "scheme_id":"nhif-xray-opg",
        "scheme_name":"nhif",
        "scheme_item_code":"5293",
        "restricted":False,
        "prices":[
          {
            "scheme_id":"nhif-xray-opg",
            "scheme_name":"nhif",
            "standard":16000
          }
        ]
      }
    ]
  },
  {
    "service_id":"xray-bitewing",
    "name":"bitewing x ray",
    "alternative_name":None,
    "type":"imaging",
    "schemes":[
      {
        "service_id":"xray-bitewing",
        "scheme_id":"cash-xray-bitewing",
        "scheme_name":"cash",
        "scheme_item_code":"xray-bitewing",
        "restricted":False,
        "prices":[
          {
            "scheme_id":"cash-xray-bitewing",
            "scheme_name":"cash",
            "standard":25000
          }
        ]
      },
      {
        "service_id":"xray-bitewing",
        "scheme_id":"nhif-xray-bitewing",
        "scheme_name":"nhif",
        "scheme_item_code":"5290",
        "restricted":False,
        "prices":[
          {
            "scheme_id":"nhif-xray-bitewing",
            "scheme_name":"nhif",
            "standard":16000
          }
        ]
      }
    ]
  },
  {
    "service_id":"xray-occlusal",
    "name":"occlusal x ray",
    "alternative_name":None,
    "type":"imaging",
    "schemes":[
      {
        "service_id":"xray-occlusal",
        "scheme_id":"cash-xray-occlusal",
        "scheme_name":"cash",
        "scheme_item_code":"xray-occlusal",
        "restricted":False,
        "prices":[
          {
            "scheme_id":"cash-xray-occlusal",
            "scheme_name":"cash",
            "standard":15000
          }
        ]
      },
      {
        "service_id":"xray-occlusal",
        "scheme_id":"nhif-xray-occlusal",
        "scheme_name":"nhif",
        "scheme_item_code":"5292",
        "restricted":False,
        "prices":[
          {
            "scheme_id":"nhif-xray-occlusal",
            "scheme_name":"nhif",
            "standard":16000
          }
        ]
      }
    ]
  },
]

users = [
  {
    "username":"nexasoft",
    "title":"master",
    "qualification":"hims",
    "designation":"hims",
    "first_name":None,
    "middle_name":None,
    "last_name":None,
    "birthdate":date.fromisoformat("2025-03-03"),
    "gender":None,
    "password":"n3x@s0ft",
    "access":None,
    "roles":["director","admin","super"]
  },
  {
    "username":"kimei01",
    "title":"dr",
    "qualification":"nta 8:degree of dental surgery",
    "designation":"dds",
    "first_name":"elisante",
    "middle_name":"ndesanjo",
    "last_name":"kimei",
    "birthdate":date.fromisoformat("2025-03-03"),
    "gender":"male",
    "password":"kimei01",
    "access":{
      "opd":["opd-consults","opd-observations","opd-injections"],
      "logistics":["logistics-admin","logistics-procurement","logistics-distribution"],
      "finances":["finances-admin","finances-reception","finances-opd-billings","finances-revenues","finances-expenditures"],
      "pharm":["pharm-reception","pharm-admin","pharm-main","pharm-opd-dispensing"],
      "imagings":["imagings-admin","imagings-reception","imagings-x-ray","imagings-ultrasound"],
      "lab":["lab-admin","lab-reception","lab-phlebotomy","lab-chemistry","lab-haematology","lab-micro","lab-para"]
    },
    "roles":["doctor","director"]
  },
  {
    "username":"hillmj",
    "title":"ms",
    "qualification":"nta 6:degree of dental surgery",
    "designation":"",
    "first_name":"maria",
    "middle_name":"jensen",
    "last_name":"hill",
    "birthdate":date.fromisoformat("1985-05-03"),
    "gender":"female",
    "password":"1234",
    "access":{"opd":["opd-reception"]},
    "roles":["receptionist"]
  },
  {
    "username":"kyandowr",
    "title":"dr",
    "qualification":"nta 8:doctor of medicine",
    "designation":"mo",
    "first_name":"wisdom",
    "middle_name":"rustico",
    "last_name":"kyando",
    "birthdate":date.fromisoformat("1995-10-06"),
    "gender":"male",
    "password":"1234",
    "access":{"opd":["opd-consults","opd-injections","opd-mtheatre"]},
    "roles":["doctor"]
  },
  {
    "username":"chazij",
    "title":"mr",
    "qualification":"nta 6:diploma of pharmacy",
    "designation":"pharm tech",
    "first_name":"justine",
    "middle_name":"",
    "last_name":"chazi",
    "birthdate":date.fromisoformat("1993-08-13"),
    "gender":"male",
    "password":"1234",
    "access":{"pharm":["opd-dispensing","main-store"]},
    "roles":["pharm technologist"]
  },
  {
    "username":"jabirs",
    "title":"ms",
    "qualification":"nta 6:degree of dental surgery",
    "designation":"cpa",
    "first_name":"fadyah",
    "middle_name":"",
    "last_name":"jabir",
    "birthdate":date.fromisoformat("2003-05-03"),
    "gender":"female",
    "password":"1234",
    "access":{"finances":["opd-billings"]},
    "roles":["cashier"]
  },
  {
    "username":"majigedj",
    "title":"ms",
    "qualification":"nta 6:degree of dental surgery",
    "designation":"rn",
    "first_name":"debora",
    "middle_name":"jacob",
    "last_name":"majige",
    "birthdate":date.fromisoformat("1993-05-23"),
    "gender":"female",
    "password":"1234",
    "access":{"opd":["opd-triage","opd-injections","opd-mtheatre"]},
    "roles":["nurse"]
  },
]

medicines = [
  {
    "medicine_id":"ibf200tab",
    "name":"ibuprofen 200mg tab",
    "type":"analgesic",
    "category":"medicine",
    "drug_class":"nsaid",
    "fda_pregnancy_category_1":"b",
    "fda_pregnancy_category_2":"b",
    "fda_pregnancy_category_3":"d",
    "prescribable":True,
    "prescription_level":"a",
    "inventory":{
      "medicine_id":"ibf200tab",
      "invoice":"inv001",
      "issuer":"nexasoft",
      "receiver":"main store",
      "issuer_previous_amount":0,
      "issuer_amount":0,
      "receiver_previous_amount":0,
      "receiver_amount":0,
      "logger":"nexasoft",
      "count":True
    },
    "requisition":{
      "requisition_id":f"default",
      "medicine_id":"ibf200tab",
      "medicine_name":"ibuprofen 200mg tab",
      "vendor":"nexasoft",
      "billed_amount":0,
      "ordered_by":"admin",
      "order_unit":"100tb",
      "order_unit_size":100,
      "ordered_amount":0,
      "unit_price":0,
      "received_amount":0,
      "received_by":"admin",
      "received_price":0
    },
    "schemes":[
      {
        "medicine_id":"ibf200tab",
        "scheme_name":"cash",
        "scheme_item_code":"ibf200tab",
        "restricted":False,
        "prices":[
          {
            "scheme_name":"cash",
            "standard":90
          }
        ]
      },
      {
        "medicine_id":"ibf200tab",
        "scheme_name":"nhif",
        "scheme_item_code":"11014",
        "restricted":False,
        "prices":[
          {
            "scheme_name":"nhif",
            "standard":31
          }
        ]
      }
    ]
  },
  {
    "medicine_id":f"ampclx500cap",
    "name":"ampicillin + cloxacillin 500mg cap",
    "type":"antibiotic",
    "category":"medicine",
    "drug_class":"penicillin",
    "fda_pregnancy_category_1":"b",
    "fda_pregnancy_category_2":"b",
    "fda_pregnancy_category_3":"b",
    "prescribable":True,
    "prescription_level":"b",
    "inventory":{
      "medicine_id":"ampclx500cap",
      "invoice":"inv001",
      "issuer":"nexasoft",
      "receiver":"main store",
      "issuer_previous_amount":0,
      "issuer_amount":0,
      "receiver_previous_amount":0,
      "receiver_amount":0,
      "logger":"nexasoft",
      "count":True
    },
    "requisition":{
      "requisition_id":f"default",
      "medicine_id":"ampclx500cap",
      "medicine_name":"ampicillin + cloxacillin 500mg cap",
      "vendor":"nexasoft",
      "billed_amount":0,
      "ordered_by":"admin",
      "order_unit":"100cp",
      "order_unit_size":100,
      "ordered_amount":0,
      "unit_price":0,
      "received_amount":0,
      "received_by":"admin",
      "received_price":0
    },
    "schemes":[
      {
        "medicine_id":"ampclx500cap",
        "scheme_name":"cash",
        "scheme_item_code":"ampclx500cap",
        "restricted":False,
        "prices":[
          {
            "scheme_name":"cash",
            "standard":200
          }
        ]
      },
      {
        "medicine_id":"ampclx500cap",
        "scheme_name":"nhif",
        "scheme_item_code":"11113",
        "restricted":False,
        "prices":[
          {
            "scheme_name":"nhif",
            "standard":137
          }
        ]
      }
    ]
  },
  {
    "medicine_id":f"mtz200tab",
    "name":"metronidazole 200mg tab",
    "type":"antibiotic",
    "category":"medicine",
    "drug_class":"nitroimidazole",
    "fda_pregnancy_category_1":"b",
    "fda_pregnancy_category_2":"b",
    "fda_pregnancy_category_3":"b",
    "prescribable":True,
    "prescription_level":"a",
    "inventory":{
      "medicine_id":"mtz200tab",
      "invoice":"inv001",
      "issuer":"nexasoft",
      "receiver":"main store",
      "issuer_previous_amount":0,
      "issuer_amount":0,
      "receiver_previous_amount":0,
      "receiver_amount":0,
      "logger":"nexasoft",
      "count":True
    },
    "requisition":{
      "requisition_id":f"default",
      "medicine_id":"mtz200tab",
      "medicine_name":"metronidazole 200mg tab",
      "vendor":"nexasoft",
      "billed_amount":0,
      "ordered_by":"admin",
      "order_unit":"100tb",
      "order_unit_size":100,
      "ordered_amount":0,
      "unit_price":0,
      "received_amount":0,
      "received_by":"admin",
      "received_price":0
    },
    "schemes":[
      {
        "medicine_id":"mtz200tab",
        "scheme_name":"cash",
        "scheme_item_code":"mtz200tab",
        "restricted":False,
        "prices":[
          {
            "scheme_name":"cash",
            "standard":100
          }
        ]
      },
      {
        "medicine_id":"mtz200tab",
        "scheme_name":"nhif",
        "scheme_item_code":"11192",
        "restricted":False,
        "prices":[
          {
            "scheme_name":"nhif",
            "standard":25
          }
        ]
      }
    ]
  },
  {
    "medicine_id":f"amx250cap",
    "name":"amoxicillin 250mg cap",
    "type":"antibiotic",
    "category":"medicine",
    "drug_class":"penicillin",
    "fda_pregnancy_category_1":"b",
    "fda_pregnancy_category_2":"b",
    "fda_pregnancy_category_3":"b",
    "prescribable":True,
    "prescription_level":"a",
    "inventory":{
      "medicine_id":"amx250cap",
      "invoice":"inv001",
      "issuer":"nexasoft",
      "receiver":"main store",
      "issuer_previous_amount":0,
      "issuer_amount":0,
      "receiver_previous_amount":0,
      "receiver_amount":0,
      "logger":"nexasoft",
      "count":True
    },
    "requisition":{
      "requisition_id":f"default",
      "medicine_id":"amx250cap",
      "medicine_name":"amoxicillin 250mg cap",
      "vendor":"nexasoft",
      "billed_amount":0,
      "ordered_by":"admin",
      "order_unit":"100cp",
      "order_unit_size":100,
      "ordered_amount":0,
      "unit_price":0,
      "received_amount":0,
      "received_by":"admin",
      "received_price":0
    },
    "schemes":[
      {
        "medicine_id":"amx250cap",
        "scheme_name":"cash",
        "scheme_item_code":"amx250cap",
        "restricted":False,
        "prices":[
          {
            "scheme_name":"cash",
            "standard":120
          }
        ]
      },
      {
        "medicine_id":"amx250cap",
        "scheme_name":"nhif",
        "scheme_item_code":"11696",
        "restricted":False,
        "prices":[
          {
            "scheme_name":"nhif",
            "standard":57
          }
        ]
      }
    ]
  },
  {
    "medicine_id":f"cipro500tab",
    "name":"ciprofloxacin 500mg tab",
    "type":"antibiotic",
    "category":"medicine",
    "drug_class":"floroquinolone",
    "fda_pregnancy_category_1":"c",
    "fda_pregnancy_category_2":"c",
    "fda_pregnancy_category_3":"c",
    "prescribable":True,
    "prescription_level":"a",
    "inventory":{
      "medicine_id":"cipro500tab",
      "invoice":"inv001",
      "issuer":"nexasoft",
      "receiver":"main store",
      "issuer_previous_amount":0,
      "issuer_amount":0,
      "receiver_previous_amount":0,
      "receiver_amount":0,
      "logger":"nexasoft",
      "count":True
    },
    "requisition":{
      "requisition_id":f"default",
      "medicine_id":"cipro500tab",
      "medicine_name":"ciprofloxacin 500mg tab",
      "vendor":"nexasoft",
      "billed_amount":0,
      "ordered_by":"admin",
      "order_unit":"100tb",
      "order_unit_size":100,
      "ordered_amount":0,
      "unit_price":0,
      "received_amount":0,
      "received_by":"admin",
      "received_price":0
    },
    "schemes":[
      {
        "medicine_id":"cipro500tab",
        "scheme_name":"cash",
        "scheme_item_code":"cipro500tab",
        "restricted":False,
        "prices":[
          {
            "scheme_name":"cash",
            "standard":300
          }
        ]
      },
      {
        "medicine_id":"cipro500tab",
        "scheme_name":"nhif",
        "scheme_item_code":"11098",
        "restricted":False,
        "prices":[
          {
            "scheme_name":"nhif",
            "standard":82
          }
        ]
      }
    ]
  },
  {
    "medicine_id":f"pcm500tab",
    "name":"paracetamol 500mg tab",
    "type":"analgesic",
    "category":"medicine",
    "drug_class":"phenol",
    "fda_pregnancy_category_1":"b",
    "fda_pregnancy_category_2":"b",
    "fda_pregnancy_category_3":"b",
    "prescribable":True,
    "prescription_level":"a",
    "inventory":{
      "medicine_id":"pcm500tab",
      "invoice":"inv001",
      "issuer":"nexasoft",
      "receiver":"main store",
      "issuer_previous_amount":0,
      "issuer_amount":0,
      "receiver_previous_amount":0,
      "receiver_amount":0,
      "logger":"nexasoft",
      "count":True
    },
    "requisition":{
      "requisition_id":f"default",
      "medicine_id":"pcm500tab",
      "medicine_name":"paracetamol 500mg tab",
      "vendor":"nexasoft",
      "billed_amount":0,
      "ordered_by":"admin",
      "order_unit":"100tb",
      "order_unit_size":100,
      "ordered_amount":0,
      "unit_price":0,
      "received_amount":0,
      "received_by":"admin",
      "received_price":0
    },
    "schemes":[
      {
        "medicine_id":"pcm500tab",
        "scheme_name":"cash",
        "scheme_item_code":"pcm500tab",
        "restricted":False,
        "prices":[
          {
            "scheme_name":"cash",
            "standard":60
          }
        ]
      },
      {
        "medicine_id":"pcm500tab",
        "scheme_name":"nhif",
        "scheme_item_code":"11024",
        "restricted":False,
        "prices":[
          {
            "scheme_name":"nhif",
            "standard":26
          }
        ]
      }
    ]
  },
  {
    "medicine_id":f"mlx10tab",
    "name":"meloxicam 10mg tab",
    "type":"analgesic",
    "category":"medicine",
    "drug_class":"nsaid",
    "fda_pregnancy_category_1":"c",
    "fda_pregnancy_category_2":"c",
    "fda_pregnancy_category_3":"d",
    "prescribable":True,
    "prescription_level":"a",
    "inventory":{
      "medicine_id":"mlx10tab",
      "invoice":"inv001",
      "issuer":"nexasoft",
      "receiver":"main store",
      "issuer_previous_amount":0,
      "issuer_amount":0,
      "receiver_previous_amount":0,
      "receiver_amount":0,
      "logger":"nexasoft",
      "count":True
    },
    "requisition":{
      "requisition_id":f"default",
      "medicine_id":"mlx10tab",
      "medicine_name":"meloxicam 10mg tab",
      "vendor":"nexasoft",
      "billed_amount":0,
      "ordered_by":"admin",
      "order_unit":"100tb",
      "order_unit_size":100,
      "ordered_amount":0,
      "unit_price":0,
      "received_amount":0,
      "received_by":"admin",
      "received_price":0
    },
    "schemes":[
      {
        "medicine_id":"mlx10tab",
        "scheme_name":"cash",
        "scheme_item_code":"mlx10tab",
        "restricted":False,
        "prices":[
          {
            "scheme_name":"cash",
            "standard":500
          }
        ]
      }
    ]
  },
  {
    "medicine_id":"povi2sol",
    "name":"povidone-iodine 2% 100ml sol",
    "type":"antiseptic",
    "category":"medical supply",
    "drug_class":"inorganic",
    "fda_pregnancy_category_1":"b",
    "fda_pregnancy_category_2":"b",
    "fda_pregnancy_category_3":"b",
    "prescribable":False,
    "prescription_level":"a",
    "inventory":{
      "medicine_id":"povi2sol",
      "invoice":"inv001",
      "issuer":"nexasoft",
      "receiver":"main store",
      "issuer_previous_amount":0,
      "issuer_amount":0,
      "receiver_previous_amount":0,
      "receiver_amount":0,
      "logger":"nexasoft",
      "count":True
    },
    "requisition":{
      "requisition_id":f"default",
      "medicine_id":"povi2sol",
      "medicine_name":"povidone-iodine 2% 100ml sol",
      "vendor":"nexasoft",
      "billed_amount":0,
      "ordered_by":"admin",
      "order_unit":"1bt",
      "order_unit_size":1,
      "ordered_amount":0,
      "unit_price":0,
      "received_amount":0,
      "received_by":"admin",
      "received_price":0
    },
    "schemes":[
      {
        "medicine_id":"povi2sol",
        "scheme_name":"cash",
        "scheme_item_code":"povi2sol",
        "restricted":False,
        "prices":[
          {
            "scheme_name":"cash",
            "standard":6000
          }
        ]
      }
    ]
  },
  {
    "medicine_id":"chx2sol",
    "name":"chlorhexidine 2% 100ml sol",
    "type":"antiseptic",
    "category":"medicine",
    "drug_class":"inorganic",
    "fda_pregnancy_category_1":"b",
    "fda_pregnancy_category_2":"b",
    "fda_pregnancy_category_3":"b",
    "prescribable":True,
    "prescription_level":"b",
    "inventory":{
      "medicine_id":"chx2sol",
      "invoice":"inv001",
      "issuer":"nexasoft",
      "receiver":"main store",
      "issuer_previous_amount":0,
      "issuer_amount":0,
      "receiver_previous_amount":0,
      "receiver_amount":0,
      "logger":"nexasoft",
      "count":True
    },
    "requisition":{
      "requisition_id":f"default",
      "medicine_id":"chx2sol",
      "medicine_name":"chlorhexidine 2% 100ml sol",
      "vendor":"nexasoft",
      "billed_amount":0,
      "ordered_by":"admin",
      "order_unit":"1bt",
      "order_unit_size":1,
      "ordered_amount":0,
      "unit_price":0,
      "received_amount":0,
      "received_by":"admin",
      "received_price":0
    },
    "schemes":[
      {
        "medicine_id":"chx2sol",
        "scheme_name":"cash",
        "scheme_item_code":"chx2sol",
        "restricted":False,
        "prices":[
          {
            "scheme_name":"cash",
            "standard":5000
          }
        ]
      }
    ]
  },
  {
    "medicine_id":f"diclo25amp",
    "name":"diclofenac 25mg/ml 3ml ampoule",
    "type":"analgesic",
    "category":"medicine",
    "drug_class":"nsaid",
    "fda_pregnancy_category_1":"b",
    "fda_pregnancy_category_2":"b",
    "fda_pregnancy_category_3":"d",
    "prescribable":True,
    "prescription_level":"a",
    "inventory":{
      "medicine_id":"diclo25amp",
      "invoice":"inv001",
      "issuer":"nexasoft",
      "receiver":"main store",
      "issuer_previous_amount":0,
      "issuer_amount":0,
      "receiver_previous_amount":0,
      "receiver_amount":0,
      "logger":"nexasoft",
      "count":True
    },
    "requisition":{
      "requisition_id":f"default",
      "medicine_id":"diclo25amp",
      "medicine_name":"diclofenac 25mg/ml 3ml ampoule",
      "vendor":"nexasoft",
      "billed_amount":0,
      "ordered_by":"admin",
      "order_unit":"10vl",
      "order_unit_size":10,
      "ordered_amount":0,
      "unit_price":0,
      "received_amount":0,
      "received_by":"admin",
      "received_price":0
    },
    "schemes":[
      {
        "medicine_id":"diclo25amp",
        "scheme_name":"cash",
        "scheme_item_code":"diclo25amp",
        "restricted":False,
        "prices":[
          {
            "scheme_name":"cash",
            "standard":3000
          }
        ]
      },
      {
        "medicine_id":"diclo25amp",
        "scheme_name":"nhif",
        "scheme_item_code":"11006",
        "restricted":False,
        "prices":[
          {
            "scheme_name":"nhif",
            "standard":195
          }
        ]
      }
    ]
  },
  {
    "medicine_id":f"mtz500sol",
    "name":"metronidazole 5mg/ml 100ml sol",
    "type":"antibiotic",
    "category":"medicine",
    "drug_class":"nitroimidazole",
    "fda_pregnancy_category_1":"b",
    "fda_pregnancy_category_2":"b",
    "fda_pregnancy_category_3":"b",
    "prescribable":False,
    "prescription_level":"a",
    "inventory":{
      "medicine_id":"mtz500sol",
      "invoice":"inv001",
      "issuer":"nexasoft",
      "receiver":"main store",
      "issuer_previous_amount":0,
      "issuer_amount":0,
      "receiver_previous_amount":0,
      "receiver_amount":0,
      "logger":"nexasoft",
      "count":True
    },
    "requisition":{
      "requisition_id":f"default",
      "medicine_id":"mtz500sol",
      "medicine_name":"metronidazole 5mg/ml 100ml sol",
      "vendor":"nexasoft",
      "billed_amount":0,
      "ordered_by":"admin",
      "order_unit":"10bt",
      "order_unit_size":10,
      "ordered_amount":0,
      "unit_price":0,
      "received_amount":0,
      "received_by":"admin",
      "received_price":0
    },
    "schemes":[
      {
        "medicine_id":"mtz500sol",
        "scheme_name":"cash",
        "scheme_item_code":"mtz500sol",
        "restricted":False,
        "prices":[
          {
            "scheme_name":"cash",
            "standard":4500
          }
        ]
      },
      {
        "medicine_id":"mtz500sol",
        "scheme_name":"nhif",
        "scheme_item_code":"11190",
        "restricted":False,
        "prices":[
          {
            "scheme_name":"nhif",
            "standard":715
          }
        ]
      }
    ]
  },
  {
    "medicine_id":f"nystsusp100k",
    "name":"nystatin 100000units/ml suspension",
    "type":"antifungal",
    "category":"medicine",
    "drug_class":"polyene",
    "fda_pregnancy_category_1":"c",
    "fda_pregnancy_category_2":"c",
    "fda_pregnancy_category_3":"c",
    "prescribable":True,
    "prescription_level":"a",
    "inventory":{
      "medicine_id":"nystsusp100k",
      "invoice":"inv001",
      "issuer":"nexasoft",
      "receiver":"main store",
      "issuer_previous_amount":0,
      "issuer_amount":0,
      "receiver_previous_amount":0,
      "receiver_amount":0,
      "logger":"nexasoft",
      "count":True
    },
    "requisition":{
      "requisition_id":f"default",
      "medicine_id":"nystsusp100k",
      "medicine_name":"nystatin 100000units/ml suspension",
      "vendor":"nexasoft",
      "billed_amount":0,
      "ordered_by":"admin",
      "order_unit":"1bt",
      "order_unit_size":1,
      "ordered_amount":0,
      "unit_price":0,
      "received_amount":0,
      "received_by":"admin",
      "received_price":0
    },
    "schemes":[
      {
        "medicine_id":"nystsusp100k",
        "scheme_name":"cash",
        "scheme_item_code":"nystsusp",
        "restricted":False,
        "prices":[
          {
            "scheme_name":"cash",
            "standard":5000
          }
        ]
      },
      {
        "medicine_id":"nystsusp100k",
        "scheme_name":"nhif",
        "scheme_item_code":"11183",
        "restricted":False,
        "prices":[
          {
            "scheme_name":"nhif",
            "standard":1925
          }
        ]
      }
    ]
  },
  {
    "medicine_id":f"diclo20gel",
    "name":"diclofenac 20g gel",
    "type":"analgesic",
    "category":"medicine",
    "drug_class":"nsaid",
    "fda_pregnancy_category_1":"c",
    "fda_pregnancy_category_2":"c",
    "fda_pregnancy_category_3":"d",
    "prescribable":True,
    "prescription_level":"a",
    "inventory":{
      "medicine_id":"diclo20gel",
      "invoice":"inv001",
      "issuer":"nexasoft",
      "receiver":"main store",
      "issuer_previous_amount":0,
      "issuer_amount":0,
      "receiver_previous_amount":0,
      "receiver_amount":0,
      "logger":"nexasoft",
      "count":True
    },
    "requisition":{
      "requisition_id":f"default",
      "medicine_id":"diclo20gel",
      "medicine_name":"diclofenac 20g gel",
      "vendor":"nexasoft",
      "billed_amount":0,
      "ordered_by":"admin",
      "order_unit":"1tu",
      "order_unit_size":1,
      "ordered_amount":0,
      "unit_price":0,
      "received_amount":0,
      "received_by":"admin",
      "received_price":0
    },
    "schemes":[
      {
        "medicine_id":"diclo20gel",
        "scheme_name":"cash",
        "scheme_item_code":"diclo20gel",
        "restricted":False,
        "prices":[
          {
            "scheme_name":"cash",
            "standard":5000
          }
        ]
      },
      {
        "medicine_id":"diclo20gel",
        "scheme_name":"nhif",
        "scheme_item_code":"11533",
        "restricted":False,
        "prices":[
          {
            "scheme_name":"nhif",
            "standard":1853
          }
        ]
      }
    ]
  },
  {
    "medicine_id":f"diclosod50tab",
    "name":"diclofenac 50mg tab",
    "type":"analgesic",
    "category":"medicine",
    "drug_class":"nsaid",
    "fda_pregnancy_category_1":"b",
    "fda_pregnancy_category_2":"b",
    "fda_pregnancy_category_3":"d",
    "prescribable":True,
    "prescription_level":"a",
    "inventory":{
      "medicine_id":"diclosod50tab",
      "invoice":"inv001",
      "issuer":"nexasoft",
      "receiver":"main store",
      "issuer_previous_amount":0,
      "issuer_amount":0,
      "receiver_previous_amount":0,
      "receiver_amount":0,
      "logger":"nexasoft",
      "count":True
    },
    "requisition":{
      "requisition_id":f"default",
      "medicine_id":"diclosod500tab",
      "medicine_name":"diclofenac 50mg tab",
      "vendor":"nexasoft",
      "billed_amount":0,
      "ordered_by":"admin",
      "order_unit":"100tb",
      "order_unit_size":100,
      "ordered_amount":0,
      "unit_price":0,
      "received_amount":0,
      "received_by":"admin",
      "received_price":0
    },
    "schemes":[
      {
        "medicine_id":"diclosod50tab",
        "scheme_name":"cash",
        "scheme_item_code":"diclosod50tab",
        "restricted":False,
        "prices":[
          {
            "scheme_name":"cash",
            "standard":200
          }
        ]
      },
      {
        "medicine_id":"diclosod50tab",
        "scheme_name":"nhif",
        "scheme_item_code":"11007",
        "restricted":False,
        "prices":[
          {
            "scheme_name":"nhif",
            "standard":20
          }
        ]
      }
    ]
  }
]
xx = [
  {
    "medicine_id":"xylitol",
    "name":"hydrogen peroxide 3% 100mls sol",
    "type":"saliva stimulant",
    "category":"medicine",
    "drug_class":"polyol",
    "fda_pregnancy_category_1":"b",
    "fda_pregnancy_category_2":"b",
    "fda_pregnancy_category_3":"b",
    "prescribable":True,
    "prescription_level":"a",
  },
  {
    "medicine_id":"azt250cap",
    "name":"azithromycin 250mg cap",
    "type":"antibiotic",
    "category":"medicine",
    "drug_class":"macrolide",
    "fda_pregnancy_category_1":"b",
    "fda_pregnancy_category_2":"b",
    "fda_pregnancy_category_3":"b",
    "prescribable":True,
    "prescription_level":"b",
  },
  {
    "medicine_id":"azt250tab",
    "name":"azithromycin 250mg tab",
    "type":"antibiotic",
    "category":"medicine",
    "drug_class":"macrolide",
    "fda_pregnancy_category_1":"b",
    "fda_pregnancy_category_2":"b",
    "fda_pregnancy_category_3":"b",
    "prescribable":True,
    "prescription_level":"b",
  },
  {
    "medicine_id":"adren1mgml",
    "name":"adrenaline injection 1mg/1ml 1ml sol",
    "type":"hormone",
    "category":"medicine",
    "drug_class":None,
    "fda_pregnancy_category_1":"b",
    "fda_pregnancy_category_2":"b",
    "fda_pregnancy_category_3":"b",
    "prescribable":True,
    "prescription_level":"b",
  },
  {
    "medicine_id":"azt500tab",
    "name":"azithromycin 500mg cap",
    "type":"antibiotic",
    "category":"medicine",
    "drug_class":"macrolide",
    "fda_pregnancy_category_1":"b",
    "fda_pregnancy_category_2":"b",
    "fda_pregnancy_category_3":"b",
    "prescribable":True,
    "prescription_level":"b",
  },
  {
    "medicine_id":"mtz20gel",
    "name":"metrondiazole 1% oral gel",
    "type":"antibiotic",
    "category":"medicine",
    "drug_class":"nitroimidazole",
    "fda_pregnancy_category_1":"b",
    "fda_pregnancy_category_2":"b",
    "fda_pregnancy_category_3":"b",
    "prescribable":True,
    "prescription_level":"a",
  },
  {
    "medicine_id":"syringe1cc",
    "name":"syringe auto-disable 1cc",
    "type":None,
    "category":"medical supply",
    "drug_class":None,
    "fda_pregnancy_category_1":"a",
    "fda_pregnancy_category_2":"a",
    "fda_pregnancy_category_3":"a",
    "prescribable":True,
    "prescription_level":"a",
  },
  {
    "medicine_id":"syringe2cc",
    "name":"syringe auto-disable 2cc",
    "type":None,
    "category":"medical supply",
    "drug_class":None,
    "fda_pregnancy_category_1":"a",
    "fda_pregnancy_category_2":"a",
    "fda_pregnancy_category_3":"a",
    "prescribable":True,
    "prescription_level":"a",
  },
  {
    "medicine_id":"syringe3cc",
    "name":"syringe auto-disable 3cc",
    "type":None,
    "category":"medical supply",
    "drug_class":None,
    "fda_pregnancy_category_1":"a",
    "fda_pregnancy_category_2":"a",
    "fda_pregnancy_category_3":"a",
    "prescribable":True,
    "prescription_level":"a",
  },
  {
    "medicine_id":"syringe5cc",
    "name":"syringe auto-disable 5cc",
    "type":None,
    "category":"medical supply",
    "drug_class":None,
    "fda_pregnancy_category_1":"a",
    "fda_pregnancy_category_2":"a",
    "fda_pregnancy_category_3":"a",
    "prescribable":True,
    "prescription_level":"a",
  },
  {
    "medicine_id":"syringe10cc",
    "name":"syringe auto-disable 10cc",
    "type":None,
    "category":"medical supply",
    "drug_class":None,
    "fda_pregnancy_category_1":"a",
    "fda_pregnancy_category_2":"a",
    "fda_pregnancy_category_3":"a",
    "prescribable":True,
    "prescription_level":"a",
  },
  {
    "medicine_id":"surgicalglove7.5",
    "name":"sterile surgical gloves latex 7.5",
    "type":None,
    "category":"medical supply",
    "drug_class":None,
    "fda_pregnancy_category_1":"a",
    "fda_pregnancy_category_2":"a",
    "fda_pregnancy_category_3":"a",
    "prescribable":True,
    "prescription_level":"a",
  },
  {
    "medicine_id":"examglove7.5",
    "name":"non-sterile examination gloves latex 7.5",
    "type":None,
    "category":"medical supply",
    "drug_class":None,
    "fda_pregnancy_category_1":"a",
    "fda_pregnancy_category_2":"a",
    "fda_pregnancy_category_3":"a",
    "prescribable":True,
    "prescription_level":"a",
  },
  {
    "medicine_id":"syringe20cc",
    "name":"syringe auto-disable 20cc",
    "type":None,
    "category":"medical supply",
    "drug_class":None,
    "fda_pregnancy_category_1":"a",
    "fda_pregnancy_category_2":"a",
    "fda_pregnancy_category_3":"a",
    "prescribable":True,
    "prescription_level":"a",
  },
  {
    "medicine_id":"hpx3sol",
    "name":"hydrogen peroxide 3% 100mls sol",
    "type":"antiseptic",
    "category":"medicine",
    "drug_class":"inorganic",
    "fda_pregnancy_category_1":None,
    "fda_pregnancy_category_2":None,
    "fda_pregnancy_category_3":None,
    "prescribable":True,
    "prescription_level":"a",
  },
  {
    "medicine_id":f"dental-floss",
    "name":"dental floss pack",
    "type":"accessory",
    "category":"medical supply",
    "drug_class":None,
    "fda_pregnancy_category_1":None,
    "fda_pregnancy_category_2":None,
    "fda_pregnancy_category_3":None,
    "prescribable":True,
    "prescription_level":None,
  },
  {
    "medicine_id":f"senso-tpaste",
    "name":"sensodyne toothpaste",
    "type":"antiseptic",
    "category":"medical supply",
    "drug_class":"inorganic",
    "fda_pregnancy_category_1":None,
    "fda_pregnancy_category_2":None,
    "fda_pregnancy_category_3":None,
    "prescribable":True,
    "prescription_level":None,
    
  },
  {
    "medicine_id":f"tbrush-softs",
    "name":"toothbrush softs",
    "type":"accessory",
    "category":"medical supply",
    "drug_class":None,
    "fda_pregnancy_category_1":None,
    "fda_pregnancy_category_2":None,
    "fda_pregnancy_category_3":None,
    "prescribable":True,
    "prescription_level":None,
  },
  {
    "medicine_id":f"floride-tpaste",
    "name":"fluoridated toothpaste",
    "type":"antiseptic",
    "category":"medical supply",
    "drug_class":"inorganic",
    "fda_pregnancy_category_1":None,
    "fda_pregnancy_category_2":None,
    "fda_pregnancy_category_3":None,
    "prescribable":True,
    "prescription_level":None,
  },
]

requisition = {
  "requisition_id":f"req{datetime.now().strftime('%y%m')}r1",
  "initiated":True,
  "vendor":"nexasoft",
  "initiated_by":"nexasoft",
  "placed":True,
  "ordered_by":"nexasoft",
  "received":True,
  "received_by":"nexasoft",
  "invoice_id":"inv000",
  "delivery_note_id":"dn000"
}

















































